- .github/workflows/helm-chart-release.yaml
add workflow to release Helm Charts. 
Due to Helm Chart releaser limitation we might need to touch `Chart.yaml` file for each chart, as the chart releaser action reacts on git history. Currently there is only a singe commit for each `Chart.yaml` file. A good starting point could be adjusting [`home`](https://github.com/eclipse-tractusx/tractusx-edc/blob/9690c0c0aa39b6707b9d62dba2e51c1d97050afa/charts/edc-controlplane/Chart.yaml#L6).
> chore: add helm chart releaser workflow

- README.md
This PR fixes the logo in the `Readme`. 
The current one points to an old version of EDC.
> fix(Readme): adds correct EDC logo link  

- build.gradle.kts
- gradle.properties
- settings.gradle.kts
updates some Gradle metadata to reflect the move to TractusX, such as `gradle.properties`, the Group ID and the project name in `settings.gradle.kts`
Move to tractusx should be reflected throughout the code base.
> chore: update project metadata

- docs/development/decision-records/2023-02-09-release-process/README.md
This PR contains a decision record about the adaptations needed to make the tractusx-edc build more repeatable and in line with established practices.
_this is a clone of https://github.com/catenax-ng/product-edc/pull/782_
> docs: create decision record about the release process

- .github/workflows/business-tests.yaml
This PR executes the `helm install` portion of the business tests in a retryable action, to guard agains transient failures and timeouts.
they are flaky
supersedes #129
> feature: make business tests more resilient

- docs/development/decision-records/2023-03-23_remove_lombok/README.md
creates a decision record about completely excising Lombok from our code base
Lombok uses undocumented and non-public APIs of the JVM and is expected to break in upcoming Java releases.
> docs: add decision record about removing Lombok

- .github/workflows/build.yaml
- .github/workflows/business-tests.yaml
- .github/workflows/draft-new-release.yaml
- .github/workflows/publish-new-release.yml
- .github/workflows/veracode.yaml
- .github/workflows/verify.yaml
- edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-memory/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
This PR changes the base image from `alpine` to `eclipse-temurin` for running java application.
It also changes the `distribution` in `temurin` when running CI jobs with the `setup-java` actions
Closes #130
> feat(baseImage): replace alpine with temurin as base image for running java applications

- docs/development/Run-business-tests-local.md
This PR adds additional info to the guide for running Business Tests locally.
It mainly adds:
- `--dependency-update` on helm install (otherwise the first time fails)
- Example of port mapping to env variables
> docs: add additional info for running business tests locally

- charts/tractusx-connector/templates/deployment-controlplane.yaml
- charts/tractusx-connector/values.yaml
This PR fixes a bug where `vault.azure.clientsecret` and `vault.azure.certificate` were not `null`, even if they aren't configured.
Closes #168
> Fix: `vault.azure.clientsecret` and `vault.azure.certificate` should be null if not configured

- .github/workflows/build.yaml
- .github/workflows/publish-new-release.yml
This PR sets a hard-coded repo URL for publishing Maven artifacts, and sets it to the "old" `catenax-ng/product-edc` repository. 
Until we can publish to OSSRH/MavenCentral (#166) we still need to publish to GitHub Packages.
GH requires that Maven coordinates be unique in the same org.  
Since both the old Product-EDC repo and our fork of Tractusx-EDC are in the `catenax-ng` org, we can only publish packages from _either one_, not both.
So for the time being we publish "into" the old repo.
Consumers of the packages **must also use the old repo url**:
```kotlin
repositories {
maven {
url = uri("https://maven.pkg.github.com/catenax-ng/product-edc")
credentials {
username = project.findProperty("gpr.user") as String? ?: System.getenv("USERNAME")
password = project.findProperty("gpr.key") as …
```
> Chore: use old repo URL for maven releases

- edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/algorithms/aes/AesAlgorithm.java
- edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/algorithms/aes/AesInitializationVectorIterator.java
- edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/algorithms/aes/ByteCounter.java
- edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/data/CryptoDataFactoryImpl.java
- edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/encrypter/AesDataEncrypterConfiguration.java
- edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/encrypter/AesDataEncrypterImpl.java
- edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/encrypter/DataEncrypterFactory.java
- edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/key/CryptoKeyFactoryImpl.java
- edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/provider/AesKeyProvider.java
- edc-extensions/data-encryption/src/main/java/org/eclipse/tractusx/edc/data/encryption/provider/CachingKeyProvider.java
- edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/algorithms/aes/AesAlgorithmTest.java
- edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/algorithms/aes/AesInitializationVectorIteratorTest.java
- edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/encrypter/DataEncrypterAesComponentTest.java
This PR is the first one of the story https://github.com/eclipse-tractusx/tractusx-edc/issues/150 lombok for the DR https://github.com/eclipse-tractusx/tractusx-edc/pull/143 .
The main target of this RP is the `edc-extensions:data-encryption` module. 
Closes #153
> feat(dataEncryption): removes lombok from data-encryption module

- docs/development/decision-records/2023-04-03_renaming_branches/README.md
This PR adds a decision record about why and how we should rename our Git branches.
> docs: decision record about renaming git branches

- edc-controlplane/edc-controlplane-postgresql/build.gradle.kts
Fixes the issue with sql pool by adding the missing dependencies.
Fixes the issue: #180
> fix: Issue with sql pool

- .github/actions/publish-docker-image/action.yml
- .github/workflows/build.yaml
- .github/workflows/publish-docker.yaml
- .markdownlint.yaml
- charts/tractusx-connector/templates/deployment-controlplane.yaml
- charts/tractusx-connector/templates/deployment-dataplane.yaml
- edc-controlplane/edc-controlplane-memory-hashicorp-vault/notice.md
- edc-controlplane/edc-controlplane-memory/notice.md
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/notice.md
- edc-controlplane/edc-controlplane-postgresql/notice.md
- edc-dataplane/edc-dataplane-azure-vault/notice.md
- edc-dataplane/edc-dataplane-hashicorp-vault/notice.md
This PR targets DockerHub when publishing Docker images instead of the GitHub Packages registry.
Eclipse projects cannot have public packages in their GH Packages registry.
- updates the deployment specs of our helm charts
- since we publish several docker images, several `notice.md` files (as required by Eclipse) were created
-
> feature: publish Docker images to DockerHub

- .github/workflows/business-tests.yaml
- charts/tractusx-connector/templates/_helpers.tpl
- charts/tractusx-connector/templates/deployment-controlplane.yaml
- charts/tractusx-connector/templates/deployment-dataplane.yaml
- charts/tractusx-connector/templates/service-controlplane.yaml
- charts/tractusx-connector/templates/service-dataplane.yaml
- charts/tractusx-connector/values.yaml
- edc-dataplane/edc-dataplane-base/build.gradle.kts
WHAT
Fixes some Helm Chart issues reported in #167 
WHY
The Helm Chart was not compatible with the version 0.3.x
> fix: Adapt Helm Chart for version 0.3.x

- edc-extensions/control-plane-adapter/README.md
The documentation of the Control-Plane-Adapter extension on how to request an asset.
The current documentation may lead to misunderstandings and is not clear enough.
> docs(control-plane-adapter): improve documentation on how to use the control-plane adapter extension

- .github/workflows/build.yaml
- .github/workflows/draft-new-release.yaml
- .github/workflows/helm-lint.yaml
- .github/workflows/publish-new-release.yml
- .github/workflows/trivy.yml
- .github/workflows/veracode.yaml
- .github/workflows/verify.yaml
Refactor GitHub output command to current version
The current command has been deprecated by GitHub Actions and will be disabled soon.
Closes #220
> refactor GitHub output command to current version

- .github/workflows/trivy.yml
This job configures the `trivy.yaml` workflow to check if an image exists, and only then does it run the scanner.
Since the `trivy` flow is executed by the `Build` flow, and because there is no way to check if docker images were actually published, the trivy flow would fail "by design" on pull requests and on forks.
Even though the issue suggests a different approach, I discovered that it is much easier to simply check for the existence of a docker image with `docker manifest inspect`, which fails if the image was not found.
Closes #239
> fix: only run trivy when docker images were actually built

- CHANGELOG.md
adds the 0.3.3 release to the CHANGELOG, fixes some markdown problems.
0.3.3 release
.
> chore: Add 0.3.3 to, and fix markdown in, CHANGELOG.md

- .github/workflows/build.yaml
- .github/workflows/publish-docker.yaml
- .github/workflows/publish-new-release.yml
- .github/workflows/veracode.yaml
- CHANGELOG.md
This PR adds a step to the `publish-new-release.yaml` workflow, that explicitly builds and pushes all Docker images with the release version as Docker tag.
For example, if we'd just released version `0.6.9`, it would create `edc-runtime-memory:0.6.9`, etc.
Due to a security restriction, workflow runs that use `GITHUB_TOKEN` cannot trigger other workflows. 
Here, this is a problem because the `publish-new-release.yaml` flow creates a Git tag, which would normally trigger another `build.yaml` flow, which would in turn build docker images with the correct version tag. Since we're using `GITHUB_TOKEN`s instead of PATs this doesn't happen.
I also simplified the use of `matrix` builds in the other flows, effectively reducing the number of jobs that are launched.
Closes #250
> feature: add explicit docker image creation during release process

- edc-controlplane/edc-controlplane-postgresql/build.gradle.kts
- edc-dataplane/edc-dataplane-azure-vault/build.gradle.kts
- edc-extensions/control-plane-adapter/build.gradle.kts
constraints: 
- `net.minidev:json-smart` to version `2.4.10`
- `org.yaml:snakeyaml` to version `2.0`
to avoid hi-level vulnerabilities detected by veracode
Closes #258
> build(deps): add constraints to avoid vulnerable transitive dependencies

- .github/workflows/veracode.yaml
- CHANGELOG.md
Rename application name for Veracode scans
The application name `product-edc` was changed to `tractusx-edc`
> chore: Rename Veracode appname in CI job

- .github/workflows/verify.yaml
Reads the SonarCloud organization and project from GH Actions vars. Also, the `SONAR_TOKEN` secret was [added to our repo by the Eclipse Helpdesk](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3047)
Have Sonar runs available upstream -> QGate requirement (?)
.
> chore(build): add GHA variables for sonar project and org

- .github/workflows/build.yaml
- .github/workflows/verify.yaml
- build.gradle.kts
Removes the Sonar job from our CI workflows, and all related configuration, such as build scripts and secrets.
According to the [documentation](https://community.sonarsource.com/t/sonarcloud-task-fails-because-of-ci-analysis-and-auto-analysis-running/22937/4) we can either have the automatic scan, _or_ a CI-triggered scan, not both.
While there is little technical difference whether we perform a manual (=CI-triggered) or automatic scan, having this done automatically seems to be the more streamlined approach to me personally.
> chore(build): remove CI-triggered sonar job

- CHANGELOG.md
- docs/migration/Version_0.3.3_0.3.4.md
Adds content to the Changelog and Migration Guide for the impending 0.3.4 release.
Documentation
.
> chore: prepare Changelog and Migr. Guide for 0.3.4

- edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/service/objectstore/ObjectStoreServiceInMemory.java
- edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/service/objectstore/ObjectStoreServiceSql.java
- edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlObjectStore.java
- edc-extensions/control-plane-adapter/src/main/java/org/eclipse/tractusx/edc/cp/adapter/store/SqlQueueStore.java
- edc-extensions/control-plane-adapter/src/test/java/org/eclipse/tractusx/edc/cp/adapter/service/ResultServiceTest.java
Deletes all `e.printStackTrace()` statements in the code base. Some were replaced with throwing a runtime exception.
Sonar [complains](https://sonarcloud.io/project/security_hotspots?id=eclipse-tractusx_tractusx-edc&sinceLeakPeriod=true). And we don't print stacktraces. Ever.
this module will go away anyways, so I didn't invest any time in coming up with an elaborate exception chain.
> chore: remove all printstacktrace statements

- .github/workflows/build.yaml
- .github/workflows/publish-new-release.yml
Publishes all Maven artefacts to OSSRH Snapshots (during normal builds on `main`) and MavenCentral (during releases). 
To have anonymous access to our Maven artefacts
- since the `build.yaml` only runs on commits directly on `main`, because it needs secrets, we will only know _after_ merging whether it has worked or not :)
Closes #166
> feat(build): publish to OSSRH Snapshots and MavenCentral

- CODE_OF_CONDUCT.md
The eclipse foundation provided a new Code of Conduct via the mailing list.
See also: https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php
Fixes #318
> docs: update code-of-conduct

- docs/kit/operation-view/page03_local_setup_controlplane.md
- docs/kit/operation-view/page04_local_setup_dataplane.md
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/README.md
- edc-controlplane/edc-controlplane-postgresql/README.md
- edc-dataplane/edc-dataplane-azure-vault/README.md
- edc-dataplane/edc-dataplane-base/README.md
- edc-dataplane/edc-dataplane-hashicorp-vault/README.md
This PR fixes misspelled `gradlew` commands in some documents.
Fixing misspelled commands enables users to copy-and-paste them.
Closes #302
> docs: fix misspelled gradlew commands in the documents

- .tractusx
Adds the `.tractusx` metafile to the repository
Needed for the QG in regards to the [TRG 2.05](https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5)
Closes #280
> chore: Add .tractusx metafile

- edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
changes the lowercase `as` to an uppercase `AS` in dockerfiles
SonarCloud complains about lowercase `as`
> chore(security): use uppercase AS in Dockerfiles

- core/edr-cache-core/build.gradle.kts
- core/edr-cache-core/src/main/java/org/eclipse/tractusx/edc/edr/core/EdrCacheCoreExtension.java
- core/edr-cache-core/src/main/java/org/eclipse/tractusx/edc/edr/core/defaults/InMemoryEndpointDataReferenceCache.java
- core/edr-cache-core/src/main/java/org/eclipse/tractusx/edc/edr/core/defaults/PersistentCacheEntry.java
- core/edr-cache-core/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
- core/edr-cache-core/src/test/java/org/eclipse/tractusx/edc/edr/core/defaults/InMemoryEndpointDataReferenceCacheTest.java
- core/edr-cache-core/src/test/java/org/eclipse/tractusx/edc/edr/core/defaults/PersistentCacheEntryTest.java
- edc-controlplane/edc-controlplane-base/build.gradle.kts
- edc-extensions/control-plane-adapter-callback/src/main/java/org/eclipse/tractusx/edc/cp/adapter/callback/InProcessCallbackRegistryExtension.java
- edc-extensions/control-plane-adapter-callback/src/main/java/org/eclipse/tractusx/edc/cp/adapter/callback/LocalCallbackExtension.java
- edc-extensions/control-plane-adapter-callback/src/main/java/org/eclipse/tractusx/edc/cp/adapter/callback/TransferProcessLocalCallback.java
- edc-extensions/control-plane-adapter-callback/src/test/java/org/eclipse/tractusx/edc/cp/adapter/callback/InProcessCallbackRegistryExtensionTest.java
- edc-extensions/control-plane-adapter-callback/src/test/java/org/eclipse/tractusx/edc/cp/adapter/callback/LocalCallbackExtensionTest.java
- edc-extensions/control-plane-adapter-callback/src/test/java/org/eclipse/tractusx/edc/cp/adapter/callback/TestFunctions.java
- edc-extensions/control-plane-adapter-callback/src/test/java/org/eclipse/tractusx/edc/cp/adapter/callback/TransferProcessLocalCallbackTest.java
- settings.gradle.kts
- spi/edr-cache-spi/build.gradle.kts
- spi/edr-cache-spi/src/main/java/org/eclipse/tractusx/edc/edr/spi/EndpointDataReferenceCache.java
- spi/edr-cache-spi/src/main/java/org/eclipse/tractusx/edc/edr/spi/EndpointDataReferenceEntry.java
- spi/edr-cache-spi/src/test/java/org/eclipse/tractusx/edc/edr/spi/EndpointDataReferenceEntryTest.java
Introduces the EDR cache and integrates it into the `TransferProcessStarted` event for storing the edr associating it with
- transferProcessId
- assetId
- contractId
This PR introduces two modules:
- `:spi:edr-cache-spi` : interfaces  and types for EDR store/cache
- `:core:edc-cache-core`: first implementation of the EDR in memory cache  
Simplification for managing the EDR 
Closes #321
> feat(ControlPlaneAdapter): edr cache integration on TransferProcessStarted event

- charts/tractusx-connector-azure-vault/README.md
- charts/tractusx-connector-azure-vault/README.md.gotmpl
- charts/tractusx-connector-memory/Chart.yaml
- charts/tractusx-connector-memory/README.md
- charts/tractusx-connector-memory/README.md.gotmpl
- charts/tractusx-connector/README.md
- charts/tractusx-connector/README.md.gotmpl
Adds a bit of documentation to all the helm charts.
QGate requirement. also, documentation is good!
Closes #353
> docs: add more documentation to the helm charts 

- .github/workflows/verify.yaml
excludes `charts/` from the markdown linter
All the markdowns there are generated, so we don't have control over their exact structure, and manually editing them will not only be tedious, upon release the README's are regenerated, which - when merging the release branch back into `main` - would create invalid markdowns and inherently break the build.
> exclude charts/ from markdown lint, as the markdowns there are generated

- charts/tractusx-connector-memory/templates/_helpers.tpl
- charts/tractusx-connector-memory/templates/deployment-runtime.yaml
- charts/tractusx-connector-memory/templates/service-runtime.yaml
- charts/tractusx-connector-memory/values.yaml
- charts/tractusx-connector/values.yaml
Rename ingress endpoint from `ids` to `protocol`
The ingress endpoint was pointing to wrong endpoint
Closes #348
> fix: Rename ingress endpoint from ids to protocol

- .github/workflows/verify.yaml
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/provider/ProviderEdcController.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/provider/ProviderServicesExtension.java
this PR adds a simple check to assert that all relevant files have a license header
Eclipse requirements
We could have done this using gradle, but doing it with `grep` is faster and can also be used for non-jave files easily. 
> build: add license header check

- edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/transferprocess/V0_0_9__Alter_TransferProcess_Remove_Transfertype.sql
Removes the renaming of the column
The column it's still called `transferprocess_properties` see [here](https://github.com/eclipse-edc/Connector/blob/6dcc371b67cd760e1b9f71e42917116d19a36874/extensions/control-plane/store/sql/transfer-process-store-sql/src/main/java/org/eclipse/edc/connector/store/sql/transferprocess/store/schema/TransferProcessStoreStatements.java#L120)
> fix(migrations): remove transferprocess_properties column renaming

- .github/actions/publish-docker-image/action.yml
- .github/workflows/build.yaml
- .github/workflows/publish-docker.yaml
- .github/workflows/publish-new-release.yml
Store the `RELEASE_VERSION` in the env to be accessible for the Docker release job.
keep consistency with other jobs
> fix(ci): store release version in env

- docs/development/decision-records/2023-05-23_activate_checkstyle/README.md
Adds a decision-record about activating checkstyle
Our styleguide mandates a certain code style, which we should enforce through automatic checks.
> docs: add decision record about activating checkstyle

- build.gradle.kts
- edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/AbstractHashicorpVaultExtension.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpCertificateResolver.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVault.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultClient.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultClientConfig.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultCreateEntryRequestPayload.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultCreateEntryResponsePayload.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultEntryMetadata.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultGetEntryResponsePayload.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultHealthCheck.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultHealthResponse.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultHealthResponsePayload.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultVaultExtension.java
- edc-extensions/hashicorp-vault/src/main/java/org/eclipse/tractusx/edc/hashicorpvault/PemUtil.java
- edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/AbstractHashicorpIt.java
- edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpCertificateResolverIntegrationTest.java
- edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpCertificateResolverTest.java
- edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultClientTest.java
- edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultHealthCheckTest.java
- edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/HashicorpVaultTest.java
- edc-extensions/hashicorp-vault/src/test/java/org/eclipse/tractusx/edc/hashicorpvault/X509CertificateTestUtil.java
- lombok.config
Removes Lombok from the HashiCorp Vault implementation, and purges the Lombok Gradle plugin from the code base.
As per Decision Record 2023-03-23, Lombok is to be removed from the code base.
Closes #154
> feat: remove Lombok from HashiCorp Vault impl

- .github/workflows/publish-maven.yaml
- build.gradle.kts
- gradle.properties
change group property
Adds a workflow that allows manually publishing to MAvenCentral/Sonatype.
Also fixes a bug with the group-id, and adds a timeout for nexus publishing.
Publishing maven artefacts failed previously due to the group bug. This will provide a convenient way to publish artifacts on-demand.
Closes #166
> build: add workflow to manually release maven artefacts

- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
Fixes the DAPS module dependency
Updates to Java 17
bugfix.
Java 17 is used by EDC and there's a D-R about it.
> chore: fix DAPS module dependency, update to java 17

- core/edr-cache-core/src/main/java/org/eclipse/tractusx/edc/edr/core/defaults/InMemoryEndpointDataReferenceCache.java
- edc-dataplane/edc-dataplane-base/build.gradle.kts
- edc-dataplane/edc-dataplane-hashicorp-vault/build.gradle.kts
- edc-dataplane/edc-dataplane-proxy-consumer-api/build.gradle.kts
- edc-dataplane/edc-dataplane-proxy-provider-api/build.gradle.kts
- edc-dataplane/edc-dataplane-proxy-provider-core/build.gradle.kts
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/helpers/EdrNegotiationHelperFunctions.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/helpers/ReceivedEvent.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/Participant.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/TestRuntimeConfiguration.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/AbstractNegotiateEdrTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/proxy/AbstractDataPlaneProxyTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/proxy/DataPlaneProxyInMemoryTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/proxy/DataPlaneProxyPostgresqlTest.java
- edc-tests/runtime/runtime-memory/build.gradle.kts
adds E2E test for the scenario of  EDR negotiation and the DataPlane Proxy
Ensure that the new feature works with all components
In the E2E test the authentication on the gateway is `none` for this test case
Closes #419
> feat(E2E): adds E2E test for CPA + DataPlaneProxy

- edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
- edc-extensions/control-plane-adapter-api/src/main/java/org/eclipse/tractusx/edc/api/cp/adapter/dto/NegotiateEdrRequestDto.java
- edc-extensions/control-plane-adapter-api/src/main/java/org/eclipse/tractusx/edc/api/cp/adapter/transform/JsonObjectToNegotiateEdrRequestDtoTransformer.java
- edc-extensions/control-plane-adapter-api/src/main/java/org/eclipse/tractusx/edc/api/cp/adapter/transform/NegotiateEdrRequestDtoToNegotiatedEdrRequestTransformer.java
- edc-extensions/control-plane-adapter-api/src/test/java/org/eclipse/tractusx/edc/api/cp/adapter/transform/JsonObjectToNegotiateEdrRequestDtoTransformerTest.java
- edc-extensions/control-plane-adapter-api/src/test/java/org/eclipse/tractusx/edc/api/cp/adapter/transform/NegotiateEdrRequestDtoToNegotiateEdrRequestTransformerTest.java
- gradle.properties
- gradle/libs.versions.toml
- resources/openapi/yaml/control-plane-adapter-api.yaml
update EDC to 0.1.0
mandatory for 0.4.1 release
Closes #432
> chore(deps): update EDC to 0.1.0

- .github/workflows/draft-new-release.yaml
- CHANGELOG.md
- charts/tractusx-connector-azure-vault/subcharts/omejdn/Chart.yaml
- charts/tractusx-connector/subcharts/omejdn/Chart.yaml
When we update the versions in our `Chart.yml` files, we need to limit the search so that the nested `daps` charts don't get updated.
this would cause the chart packaging to fail, since the subchart version, and the one referenced in the parent charts don't match anymore.
for example see: https://github.com/eclipse-tractusx/tractusx-edc/actions/runs/5132313351/jobs/9233450666
> fix: limit search for Chart.yaml to avoid subchart updates

- charts/tractusx-connector/README.md.gotmpl
Inside the `tractusx-connector` chart the wrong chart is referenced in the installations docs.
This PR will change the go-template to the correct chart name.
<hr />
Marco Lecheler [marco.lecheler@mercedes-benz.com](mailto:marco.lecheler@mercedes-benz.com) Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md))
> chore(helm): fix tractusx-connector chart install cmd

- charts/tractusx-connector-azure-vault/templates/ingress-controlplane.yaml
- charts/tractusx-connector-azure-vault/templates/ingress-dataplane.yaml
- charts/tractusx-connector-memory/templates/ingress-runtime.yaml
- charts/tractusx-connector/templates/ingress-controlplane.yaml
- charts/tractusx-connector/templates/ingress-dataplane.yaml
If in a `ingresses` item list element no `annotations` key is given the templating fails.
Then a empty dictionary `{}` needs to be passed.
```yaml
dataplane:
ingresses:
- enabled: true
hostname: "edc-data.local"
annotations: {} # <-- required
```
This PR will change that - and will allow to omit this value if not required.
Inside the templating a variable will used to set a default (empty dict) if no annotations are given.
If no `dataplane.ingresses[*].annotations` is set following error message will be returned when Helm chart is templated:
> Error: template: tractusx-connector/templates/ingress-dataplane.yaml:57:18: executing "tractusx-connector/templates/ingress-dataplane.yaml" at <.annotations>: wrong type for value; expected map[string]interface {}; got interface {}
This also occurs …
> feat(helm): allow to omit ingress annotations key

- edc-extensions/cx-policy/build.gradle.kts
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/common/AbstractVpConstraintFunction.java
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/common/JsonLdTypeFunctions.java
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/common/JsonLdValueFunctions.java
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/common/PolicyNamespaces.java
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/common/PolicyScopes.java
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementConstraintFunction.java
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/summary/SummaryConstraintFunction.java
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/summary/SummaryConstraintFunctionsProvider.java
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/summary/SummaryTokenConstraintFunction.java
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/summary/SummaryTokenPolicyFunction.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/common/AbstractVpConstraintFunctionTest.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/common/JsonLdTypeFunctionsTest.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/common/JsonLdValueFunctionsTest.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/fixtures/JsonLdTextFixtures.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/fixtures/W3CVcContext.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/fixtures/W3cVcContext.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementConstraintFunctionTest.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/framework/PcfCredential.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/framework/UseCaseContext.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/summary/SummaryConstraintFunctionTest.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/summary/SummaryConstraintFunctionsProviderTest.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/summary/SummaryContext.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/summary/SummaryCredential.java
- gradle/libs.versions.toml
- settings.gradle.kts
This PR provides an initial implementation of SSI policies per this [specification](https://github.com/eclipse-tractusx/ssi-docu/blob/main/docs/architecture/cx-3-2/edc/policy.definitions.md) and the [Summary Credential](https://github.com/eclipse-tractusx/ssi-docu/blob/main/docs/credentials/summary/summary.vc.md).
The CX policy module contains functions for working with Json-Ld structures. These functions (`JsonLdTypeFunctions` and `JsonLdValueFunctions`) will likely be refactored into a common module and shared with the new SSI-based `IdentityService` in a subsequent PR.
Closes #476
> feat: Initial implementation of Catena-X policies

- docs/development/decision-records/2023-06-13_use_of_iron_library/README.md
Adds a decision record mandating the use of `iron-verifiable-credentials`.
traceable decisions.
.
> docs: add decision record about the use of iron-verifiable-credentials

- edc-extensions/business-partner-validation/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/AbstractBusinessPartnerValidation.java
> chore: fix tests

- charts/tractusx-connector-azure-vault/subcharts/omejdn/templates/configmap.yaml
- charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
- charts/tractusx-connector-azure-vault/values.yaml
- charts/tractusx-connector-memory/example.yaml
- charts/tractusx-connector-memory/subcharts/omejdn/templates/configmap.yaml
- charts/tractusx-connector-memory/templates/deployment-runtime.yaml
- charts/tractusx-connector-memory/values.yaml
- charts/tractusx-connector/subcharts/omejdn/templates/configmap.yaml
- charts/tractusx-connector/templates/deployment-controlplane.yaml
- charts/tractusx-connector/values.yaml
- docs/samples/example-dataspace/daps/templates/configmap.yaml
- docs/samples/example-dataspace/plato-values.yaml
- docs/samples/example-dataspace/sokrates-values.yaml
- edc-tests/deployment/src/main/resources/helm/tractusx-connector-azure-vault-test.yaml
- edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml
This PR changes the daps url behavior.
Instead of using a `fullnameOverride` to set the service name fix to `daps` the name is now including the `.Release.Name` variable.
This helps Helm chart users to deploy multiple separate instances of the tractusx-connector chart in the same namespace.
Also the naming convention of pods / services will follow the others.
```bash
$ kubectl get pod # without PR change
NAME                                                         READY   STATUS    RESTARTS   AGE
daps-7677896f79-rkpzl                                        0/1     Running   0          5s
myrelease-tractusx-connector-controlplane-86784bc6c4-rxcdx   0/1     Running   0          5s
myrelease-tractusx-connector-dataplane-7964df994-jqx2d       0/1     Running   0          5s
postgresql-0 …
```
> feat(helm): use release.name inside daps dependency

- charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
- charts/tractusx-connector-azure-vault/values.yaml
- charts/tractusx-connector/templates/deployment-controlplane.yaml
- charts/tractusx-connector/templates/deployment-dataplane.yaml
- charts/tractusx-connector/values.yaml
- edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml
This PR changes the psql url behavior.
Instead of using a `fullnameOverride` to set the service name fix to `postgresql` the name is now including the `.Release.Name` variable.
This helps Helm chart users to deploy multiple separate instances of the tractusx-connector chart in the same namespace.
Also the naming convention of pods / services will follow the others.
```bash
$ kubectl get pod # without PR change
NAME                                                         READY   STATUS    RESTARTS   AGE
daps-7677896f79-rkpzl                                        0/1     Running   0          5s
myrelease-tractusx-connector-controlplane-86784bc6c4-rxcdx   0/1     Running   0          5s
myrelease-tractusx-connector-dataplane-7964df994-jqx2d       0/1     Running   0          5s
postgresql-0 …
```
> feat(helm): use release.name inside psql dependency

- charts/tractusx-connector/templates/deployment-controlplane.yaml
- charts/tractusx-connector/templates/deployment-dataplane.yaml
- charts/tractusx-connector/values.yaml
- edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml
This PR changes the HashiCorp Vault url behavior.
Instead of using a `fullnameOverride` to set the service name fix to `vault` the name is now including the `.Release.Name` variable.
This helps Helm chart users to deploy multiple separate instances of the tractusx-connector chart in the same namespace.
Also the naming convention of pods / services will follow the others.
```bash
$ kubectl get pod # without PR change
NAME                                                         READY   STATUS    RESTARTS   AGE
daps-7677896f79-rkpzl                                        0/1     Running   0          5s
myrelease-tractusx-connector-controlplane-86784bc6c4-rxcdx   0/1     Running   0          5s
myrelease-tractusx-connector-dataplane-7964df994-jqx2d       0/1     Running   0          5s …
```
> feat(helm): use release.name inside vault dependency

- edc-tests/deployment/src/main/resources/helm/tractusx-connector-azure-vault-test.yaml
fixes the test values file for the Azure+Postgres chart test.
during recent refactorings, this particular file was forgotten.
- azure tests don't run in pull requests. here is a successful run in my fork: https://github.com/paullatzelsperger/tractusx-edc/actions/runs/5291867576
> fix: construction of postgresql jdbc url

- .github/workflows/publish-new-release.yml
This PR improves the release workflow by changing the logic where the new snapshot version is selected.
Assuming `<major>.<minor>.<patch>` versions, previously, we always incremented the `patch` version, regardless of what the input was. So `0.5.0-rc1` would have resulted in a `0.5.1-SNAPSHOT`, which is incorrect.
Now, we only increase the `<patch>` version, if there is no `-rc1` or anything:
- `0.5.0` becomes `0.5.1-SNAPSHOT`
- `0.5.0-rc1` becomes `0.5.0-SNAPSHOT`
The existing logic would have handled release candidates etc. incorrectly.
Closes # <-- _insert Issue number if one …
> feat(build): only increase patch version on final releases

- charts/tractusx-connector-azure-vault/README.md
- charts/tractusx-connector-azure-vault/README.md.gotmpl
- charts/tractusx-connector-azure-vault/values.yaml
- charts/tractusx-connector-memory/README.md
- charts/tractusx-connector-memory/README.md.gotmpl
- charts/tractusx-connector-memory/values.yaml
- charts/tractusx-connector/README.md
- charts/tractusx-connector/README.md.gotmpl
- charts/tractusx-connector/values.yaml
Improves the `README.md` files (or rather: the `*.gotmpl`) of our helm charts explaining some details about SSI.
better documentation
- removed the `controlplane.ssi.endpoint.audience` setting, as this always defaults to the callback URL
> docs: add quick guide to the charts' README

- CHANGELOG.md
adds the soon-to-be-created `0.5.0-rc2` version to the changelog.
changelog
- there will not be a dedicated migration guide, because there is no significant difference to `0.5.0-rc1`
> chore: prepare Changelog

- .github/workflows/deployment-test.yaml
- .github/workflows/publish-new-release.yml
- .github/workflows/publish.yaml
- .github/workflows/run-all-tests.yml
- .github/workflows/trivy.yml
- .github/workflows/verify.yaml
This PR restructures our CI pipeline in the following aspects:
- adds a `test-all` workflow, that starts `verify` and `deployment-test` 
- rename `build` -> `publish`, run only after `test-all` has completed
- when releasing, the GitHub Release is created only _after_ all publications were successful
this causes the CI to publish artefacts _only after_ all tests were successful, avoiding partial or even broken artefacts
- concurrency handling is done by the `test-all` workflow
Closes #229
> refactor(build): restructure and serialize the build pipeline

- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/negotiation/AbstractContractNegotiateTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/negotiation/SsiContractNegotiationInMemoryTest.java
adds E2E test for `ContractNegotiation` failure using SSI flow and policies
Closes #528
> feat(tests): adds SSI E2E test for ContractNegotiation failure 

- .github/workflows/publish.yaml
In a previous PR the wrong workflow name was used to trigger the publish job.
the publish workflow is triggered by the test job.
Closes #229
> fix(build): use correct workflow name to trigger publish

- build.gradle.kts
- settings.gradle.kts
This is an attempt to enable Coverage Reports via SonarQube, by enabling the test coverage report generation.
No coverage reports where generated.
It is unclear which gradle tasks the Sonar server executes before running the analysis, so this is really more of an attempt.
Should this not be successful, we'll deactivate the automatic Sonar analysis, and replace it with an explicit `./gradlew sonar ...` task, the way it was in the past.
Closes #389
> fix(test): enable coverage report via Sonar

- edc-extensions/edr-cache-sql/src/main/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCache.java
- edc-extensions/edr-cache-sql/src/test/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheTest.java
- spi/edr-cache-spi/src/testFixtures/java/org/eclipse/tractusx/edc/edr/spi/EndpointDataReferenceCacheBaseTest.java
Replaces the prefix for EDRs, from `edr__` to `edr--`. 
Some vaults, such as Azure KeyVault, are quite particular about allowed characters, and disallow "__"
- a corresponding issue in https://github.com/eclipse-edc/technology-azure will be opened, that improves the sanitization process.
> fix: replace '__' with '--' in the Sql EDR Store

- .github/workflows/verify.yaml
- core/json-ld-core/src/main/java/org/eclipse/tractusx/edc/jsonld/JsonLdExtension.java
- core/json-ld-core/src/main/resources/document/summary-vc-context-v1.jsonld
- edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/api/MiwApiClientImpl.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tag/MiwIntegrationTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/catalog/MiwSsiCatalogTest.java
- edc-tests/e2e-tests/src/test/resources/db.sh
- edc-tests/e2e-tests/src/test/resources/docker-compose.yml
- edc-tests/e2e-tests/src/test/resources/miw_test_realm.json
Adds an E2E test with real MIW running. The test is a single `CatalogRequest` with one participant asking the catalog to self.  
Due to the non-trivial seed of credentials in MIW for now it's ok just to have only this flow. 
It will still be tested the real communication with MIW, Keycloak and new policy based on credentials.
The used image for MIW is 
```
ghcr.io/catenax-ng/tx-managed-identity-wallets_miw_service:0.0.1-snapshot.2994d69
```
Catching regressions 
Closes #543
> feat(SSI): adds E2E test for Catalog request with real MIW

- edc-extensions/provision-additional-headers/README.md
- edc-extensions/provision-additional-headers/build.gradle.kts
- edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersProvisioner.java
- edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersResourceDefinition.java
- edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersResourceDefinitionGenerator.java
- edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/ProvisionAdditionalHeadersExtension.java
- edc-extensions/provision-additional-headers/src/test/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersProvisionerTest.java
- edc-extensions/provision-additional-headers/src/test/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersResourceDefinitionGeneratorTest.java
- edc-extensions/provision-additional-headers/src/test/java/org/eclipse/tractusx/edc/provision/additionalheaders/ProvisionAdditionalHeadersExtensionTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractHttpConsumerPullWithProxyTest.java
Add a `Edc-Bpn` header to the dataplane call to the http data source.
It's needed for authentication and auditing purposes by the Use Cases
- lightened the extension tests, passing from a "component" to a "unit" one, since the e2e behavior is already verified by e2e-tests.
Closes #539
> feat: add BPN as header in the call from dataplane to http source

- CHANGELOG.md
Markdown lint fix on changelog after release
> chore(changelog): fix md lint after release

- charts/tractusx-connector-azure-vault/templates/deployment-dataplane.yaml
- charts/tractusx-connector-memory/templates/deployment-runtime.yaml
- charts/tractusx-connector/templates/deployment-controlplane.yaml
- docs/samples/example-dataspace/plato-values.yaml
- docs/samples/example-dataspace/sokrates-values.yaml
It turned out that this https://github.com/eclipse-tractusx/tractusx-edc/discussions/556 was caused by the default security context that prevented the JSON-LD extensions to properly load the cached context from disks.
Logs:
```
WARNING  Failed to register cached json-ld document: Cannot read resource document/credential-v1.jsonld: 
WARNING  Failed to register cached json-ld document: Cannot read resource document/summary-vc-context-v1.jsonld: 
WARNING  Failed to register cached json-ld document: Cannot read resource document/summary-vc-context-v1.jsonld:
```
This can be fixed by allowing the setting the property in the securityContext `readOnlyRootFilesystem:false` so that the process can write in the `/tmp` directory. With this PR it will not be needed anymore since in all charts a …
> fix(charts): add temporary emptyDir volume to the controlplane charts

- charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
- charts/tractusx-connector/templates/deployment-dataplane.yaml
- docs/samples/example-dataspace/plato-values.yaml
- docs/samples/example-dataspace/sokrates-values.yaml
Additional fix for https://github.com/eclipse-tractusx/tractusx-edc/pull/564
> fix(charts): add temp volume for tmp directory

- .github/workflows/verify.yaml
- DEPENDENCIES
Updates the `DEPENDENCIES` file, adds a check to the CI that verifies the DEPENDENCIES file is up-to-date
compliance with Eclipse
- the job will issue a warning if `restricted` dependencies are found
- the job will issue an error and fail if `rejected` dependencies are found
- currently there are still IPLab reviews open: 
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9261
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9262
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9263
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9264
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9265
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9266
- …
> feat: update DEPENDENCIES, add check to CI

- edc-extensions/ssi/ssi-miw-credential-client/README.md
Adds more information on MIW credential module
Closes #575
> feat(docs): adds more information on MIW credential module

- edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/api/MiwApiClientImpl.java
- edc-extensions/ssi/ssi-miw-credential-client/src/test/java/org/eclipse/tractusx/edc/iam/ssi/miw/api/MiwApiClientImplTest.java
Adds response body in case errors in MIW response
Better diagnostics when dealing on errors in MIW
Closes #573
> feat(MIWClient): adds response body in case errors in MIW response

- .github/workflows/draft-new-release.yaml
- .github/workflows/helm-lint.yaml
- .github/workflows/kics.yml
- .github/workflows/publish-new-release.yml
- .github/workflows/verify.yaml
Reformats all GH Workflow yaml files. Essentially, it removes pointless newlines that just make YAML files less readable and waste space.
Consistency. Also because it looked ugly.
> chore: reformat workflow yaml files

- docs/development/decision-records/2023-07-06_removing_manual_changelog/README.md
adds a decision record about the removal of the manually curated CHANGELOG.md file.
it's tedious, error prone and utterly unnecessary.
there will be an automatically generated CHANGELOG.
> docs: add decision record about removing the CHANGELOG.md

- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/AbstractNegotiateEdrTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/negotiation/SsiContractNegotiationInMemoryTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractHttpConsumerPullWithProxyTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/SsiHttpConsumerPullWithProxyInMemoryTest.java
- edc-tests/edc-dataplane-proxy-e2e/src/test/java/org/eclipse/tractusx/edc/dataplane/proxy/e2e/DpfProxyEndToEndTest.java
this PR attempts to fix some of the flaky e2e tests we saw in the past.
The problem there was that the `MockWebServer` could not be started, due to an "Address already in use" error.
We don't exactly know where this is coming from, so this is really more of an "exploratory" PR
It should be noted that this goes somewhat _against_ the recommended use of the `MockWebServer`, which requires it to be re-instantiated on every test.
Flaky e2e tests
other solution ideas are
- switching to another mockwebserver. In EDC we use the Netty MockServer, which seems to not have these problems.
- adding a `RetryPolicy` to the instantiation and starting of the mock webserver: this would guard against transient errors such as timing issues
- use randomized ports for _every_ instance: would probably the …
> fix(test): converted some MockWebServer to long-running instances

- docs/development/postman/collection.json
This PR align the postman collection in the latest version, due some additional checks in place on EDC 0.1.3 in mgmt APIs:
- sortField cannot be empty on catalogue request
- type dataDestination in transfer request should not be inside the `properties` field but at the first level
- connectorId in transfer request is mandatory
- aligned the policy field in NegotiationInitiateRequest
Docs
> feat(docs): updates postman collection

- docs/migration/Version_0.4.x_0.5.x.md
Updates the migration guide with some docs about the changes in EDC upstream 0.1.3 for the
consumer pull flow
docs
> feat(docs): add changes in consumer pull flow in the migration guide

- core/json-ld-core/src/main/java/org/eclipse/tractusx/edc/jsonld/JsonLdExtension.java
- core/json-ld-core/src/main/resources/document/security-ed25519-2020.jsonld
- core/json-ld-core/src/main/resources/document/security-jws-2020.jsonld
- core/json-ld-core/src/test/java/org/eclipse/tractusx/edc/jsonld/JsonLdExtensionTest.java
Add `JWS` security context in cache
If https/http loader are disabled the expansion will fail
> chore(SSI): add security context in cache

- docs/migration/Version_0.4.x_0.5.x.md
adds a note about the `cid` removal in the migration guide
> chore(docs): adds a note about the `cid` removal

- .github/dependabot.yml
Decreases the dependabot frequency to `weekly`
there is no point in doing this daily, seeing that we also have update the `DEPENDENCIES` file everytime.
> build: decrease dependabot frequency to 'weekly'

- edc-dataplane/edc-dataplane-base/build.gradle.kts
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/README.md
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/build.gradle.kts
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/DataPlaneProxyConsumerApiExtension.java
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/ConsumerAssetRequestController.java
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/model/AssetRequest.java
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/test/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/model/AssetRequestTest.java
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/test/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/model/ConsumerAssetRequestControllerTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/Participant.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/proxy/AbstractDataPlaneProxyTest.java
- edc-tests/edc-dataplane-proxy-e2e/build.gradle.kts
- edc-tests/edc-dataplane-proxy-e2e/src/test/java/org/eclipse/tractusx/edc/dataplane/proxy/e2e/DpfProxyEndToEndTest.java
The `endpointUrl` in `RequestAsset` can now be omitted and the `Edr#endpointUrl` will be used.
In this scenario additional properties can be used for enriching the asset request.
- `pathSegments` 
- `queryParameters`
Which they will be used for composing the final asset request to the provider dataplane
For use case where the asset `endpointUrl` is not known
Also in this PR the APIs under proxy are now protected with the token based authentication 
Closes #625
> feat(DataPlaneConsumerProxy): adds support for data plane provider url

- .github/workflows/kics.yml
suppress noisy kics warning on MIW tests docker-compose
PR pollution
> chore: suppress noisy kics warning on miw tests docker-compose

- .github/actions/publish-docker-image/action.yml
- build.gradle.kts
- edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
Downloads the OpenTelemetry Agent jar "outside" of the Dockerfile. This is actually done in two locations:
1. the `build.gradle.kts` file: a Gradle task is added for this
2. the `publish-docker-image` action: a GH Actions step is added, because when publishing we don't use the Gradle Docker task
Downloading the OTEL Agent inside Docker required adding `curl` first, and due to security restrictions that required a fixed version. APK, Alpine Linux's package manager, seems to not keep older versions around, which caused the build to break whenever a new version of `curl` was released.
- Docker can't use resources outside of its build context, that is why the Gradle task downloads the `opentelemetry-javaagent.jar` once per project, directly to each project's `build/` folder. 
Closes #686
> feat: download opentelemetry jar outside of Dockerfile

- edc-extensions/edr/edr-api/build.gradle.kts
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/EdrApi.java
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/EdrApiExtension.java
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/EdrController.java
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/validation/NegotiateEdrRequestDtoValidator.java
- edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/EdrControllerTest.java
- edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/validation/NegotiateEdrRequestDtoValidatorTest.java
- gradle/libs.versions.toml
Adds validator when initiating a new EDR negotiation request
consistency
In all EDRs api the call to expand/compact where removed, since there is the interceptor that does that already
Closes #702
> feat(edrs): add init edr request api validator

- edc-extensions/edr/edr-api/build.gradle.kts
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/EdrApi.java
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/schema/EdrSchema.java
- edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/EdrApiTest.java
- gradle/libs.versions.toml
Add schema and examples for EDR API
documentation
Closes #704
> feat(edrs): add EDR api schema and example

- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/EdrApi.java
Fix missing openapi parameter. The rest of the issues are from upstream. Will look at them next.
Our openapi documentation has errors and cannot be parsed right now.
> Fix: Add missing OpenAPI parameter

- charts/tractusx-connector-azure-vault/README.md
- charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
- charts/tractusx-connector-azure-vault/templates/deployment-dataplane.yaml
- charts/tractusx-connector-azure-vault/values.yaml
- charts/tractusx-connector-memory/README.md
- charts/tractusx-connector-memory/templates/deployment-runtime.yaml
- charts/tractusx-connector-memory/values.yaml
- charts/tractusx-connector/README.md
- charts/tractusx-connector/templates/configmap-customcacerts.yaml
- charts/tractusx-connector/templates/deployment-controlplane.yaml
- charts/tractusx-connector/templates/deployment-dataplane.yaml
- charts/tractusx-connector/values.yaml
Add Helm chart value (`customCaCerts`) to support adding additional custom ca-certs to the control- and dataplane pods.
If your company is using a certificate authority which is not inside the common `/opt/java/openjdk/lib/security/cacerts` file connections will not be trusted.
A connection in between will then fail in lack of trusted certificates.
When only using public signed certificate you will not need this value.
With this change you will be able to specify additional custom certificates as follows in your values file:
```yaml
customCaCerts:
YourCompany.pem: |
-----BEGIN CERTIFICATE-----
MIICuzCCAaMCAQAwMzELMAkGA1UEBhMCREUxEDAOBgNVBAgMB0JhdmFyaWExEjAQ
...
-----END CERTIFICATE-----
```
When one or more certificates are added to the dict they will be each added via a initContainer and …
> feat(helm): add customCaCerts value

- .github/workflows/verify.yaml
- DEPENDENCIES
- core/edr-cache-core/build.gradle.kts
- core/edr-cache-core/src/main/java/org/eclipse/tractusx/edc/edr/core/defaults/EdrCacheEntryPredicateConverter.java
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/test/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/model/ConsumerAssetRequestControllerTest.java
- edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/transform/EndpointDataReferenceToDataAddressTransformerTest.java
- edc-extensions/edr/edr-callback/src/test/java/org/eclipse/tractusx/edc/callback/ContractNegotiationCallbackTest.java
- edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/contractnegotiation/V0_0_7__Alter_ContractNegotiation_AddPendingField.sql
- edc-extensions/transferprocess-sftp-client/src/main/java/org/eclipse/tractusx/edc/transferprocess/sftp/client/SftpDataSinkFactory.java
- edc-extensions/transferprocess-sftp-client/src/main/java/org/eclipse/tractusx/edc/transferprocess/sftp/client/SftpDataSourceFactory.java
- edc-extensions/transferprocess-sftp-client/src/test/java/org/eclipse/tractusx/edc/transferprocess/sftp/client/SftpDataSinkFactoryTest.java
- edc-extensions/transferprocess-sftp-client/src/test/java/org/eclipse/tractusx/edc/transferprocess/sftp/client/SftpDataSourceFactoryTest.java
- edc-extensions/transferprocess-sftp-common/src/main/java/org/eclipse/tractusx/edc/transferprocess/sftp/common/SftpDataAddress.java
- edc-extensions/transferprocess-sftp-common/src/test/java/org/eclipse/tractusx/edc/transferprocess/sftp/common/SftpDataAddressTest.java
- gradle.properties
- gradle/libs.versions.toml
Upgrades to EDC 0.2.1 fixing some compiler errors in the process.
Limit the technical debt
- fixed som `final XYZ -> var` in the process
- Updates DEPENDENCIES
- Re-enables Postgres E2E Tests
- Removing the JWS2020 Suite will be done in another PR (it has been upstreamed)
> chore: update to EDC 0.2.1

- charts/tractusx-connector-azure-vault/LICENSE
- charts/tractusx-connector-memory/LICENSE
- charts/tractusx-connector/LICENSE
Copies the LICENSE file to all charts. That way they get packaged during release.
all published charts should contain a LICENSE file
Closes #718
> chore: add LICENSE file to all charts

- core/json-ld-core/build.gradle.kts
- core/json-ld-core/src/main/java/org/eclipse/tractusx/edc/jsonld/JsonLdExtension.java
- core/json-ld-core/src/main/resources/document/edc-v1.jsonld
- core/json-ld-core/src/main/resources/document/tx-v1.jsonld
- edc-extensions/bpn-validation/bpn-validation-core/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/BusinessPartnerValidationExtension.java
- edc-extensions/cx-policy/build.gradle.kts
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/summary/SummaryConstraintFunctionsProvider.java
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/dto/NegotiateEdrRequestDto.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/helpers/PolicyHelperFunctions.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/catalog/MiwSsiCatalogTest.java
- edc-tests/e2e-tests/src/test/resources/framework-policy.json
- spi/core-spi/src/main/java/org/eclipse/tractusx/edc/edr/spi/CoreConstants.java
Add fix for `leftOperand` when using `@context` of odrl which get expanded with wrong namespace.
to fix this the functions are registered also in the `tx` namespace and the final usage will be 
```json
{
"@context": {
"@vocab": "https://w3id.org/edc/v0.0.1/ns/",
"tx" : "https://w3id.org/tractusx/v0.0.1/ns/"
},
"@type": "PolicyDefinition",
"@id": "{{policy-id'}}",
"policy": {
"@context": "http://www.w3.org/ns/odrl.jsonld",
"permission": {
"action": "use",
"constraint": {
"leftOperand": "tx:Dismantler",
"operator": "eq",
"rightOperand": "active"
}
}
}
}
```
bugfix
In addition in order to simplify policy expressions 2 context where drafted and added in the cache:
- tractusx 
- edc 
This two for the moment are just an exploration, once we decided that they works well we can proceed to …
> fix: add binding to tx namespace for credential policy

- .github/workflows/trivy.yml
- DEPENDENCIES
Uses the new recommended command to inspect an image's manifest. 
the old `docker manifest inspect` required `push` rights on DockerHub for some weird reason. thus, we would have had to login before, which does not make sense.
> fix(build): fix docker image inspect command

- edc-extensions/bpn-validation/bpn-validation-core/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/LegacyBusinessPartnerValidationExtension.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/helpers/PolicyHelperFunctions.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/catalog/AbstractCatalogTest.java
Register the legacy `BusibessPartnerNumber` as constraint key with the namespaced version
consistency
Closes #729
> fix(legacyBpn): register also the namespaced version of the constraint key

- charts/tractusx-connector-azure-vault/README.md
- charts/tractusx-connector-azure-vault/templates/deployment-dataplane.yaml
- charts/tractusx-connector-azure-vault/values.yaml
- charts/tractusx-connector/README.md
- charts/tractusx-connector/templates/deployment-dataplane.yaml
- charts/tractusx-connector/values.yaml
- docs/samples/example-dataspace/plato-values.yaml
- docs/samples/example-dataspace/sokrates-values.yaml
- edc-tests/deployment/src/main/resources/helm/tractusx-connector-azure-vault-test.yaml
- edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml
api key config missing in dataplane for proxy
bug, consistency
Closes #734
> fix:(charts): api key config missing in dataplane for proxy

- CHANGELOG.md
recovered CHANGELOG.md from 0.5.0-rc5
copied generated changelogs from releases 0.5.0 and 0.5.1 
added links
fixed all linting errors in the old file
Closes
#723
> chore(changelog): updated CHANGELOG.md with 0.5.0 and 0.5.1

- edc-controlplane/edc-controlplane-memory-hashicorp-vault/notice.md
- edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-azure-vault/notice.md
- edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/notice.md
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-runtime-memory/notice.md
- edc-controlplane/edc-runtime-memory/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-azure-vault/notice.md
- edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-hashicorp-vault/notice.md
- edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
upgrade docker base images to `eclipse-temurin:17.0.8_7-jre-alpine`
security vulnerabilities in the current image
Closes #742
> chore: upgrade docker base images

- build.gradle.kts
Fixes the publish artifact jobs
https://github.com/eclipse-tractusx/tractusx-edc/actions/runs/6073175379
After this #749, the changes in the `build.gradle.kts` made the publish artifacts failing
> chore: fix create docker images jobs

- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
removes 
```kotlin
val annotationProcessorVersion: String by project
val metaModelVersion: String by project
val edcGradlePluginsVersion: String by project
```
and the version from `gradle.properties` by using the centralized version in the catalog
refactoring
Closes #753
> refactor: centralize edc version

- docs/samples/edr-api-overview/edr-api-overview.md
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/README.md
Enriches the EDR management API with docs on how to use the `ConsumerDataPlaneProxy` for fetching data
docs
Closes #391
> docs: enriched the EDR API overview with transfer documentation

- docs/development/decision-records/2023-09-08_issue_quality_stalebot/README.md
Adds a decision record about the planned improvement of our GH issue quality.
documentation
> docs: decision record about issue quality

- DEPENDENCIES
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/EdrController.java
- edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/EdrControllerTest.java
Fix the EDR filtering by providerId
bug
Closes #758
> fix: edr filtering by providerId

- charts/tractusx-connector-azure-vault/README.md
- charts/tractusx-connector-azure-vault/values.yaml
- charts/tractusx-connector-memory/README.md
- charts/tractusx-connector-memory/values.yaml
- charts/tractusx-connector/README.md
- charts/tractusx-connector/values.yaml
Add default values to helm charts
Because of QG checks [TRG 5.01](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01/)
- Cleanup daps values from memory chart
- Recreate README.md files
Closes #724
> chore: add default values to helm charts

- gradle.properties
Bumps the connector version to 0.6.0-SNAPSHOT
Next product increment
- chart versions etc. will get bumped during the release process
> chore: bump version to 0.6.0-SNAPSHOT

- DEPENDENCIES
- edc-extensions/bpn-validation/README.md
Fix an url to the OpenAPI specification.
documentation
> fix(docs): use correct url in docu

- edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/SsiMiwOauth2ClientExtension.java
I have adjusted the error message in the `SsiMiwOauth2ClientExtension`.
#777
Because the statement that the secret could not be found in the Vault can be confusing. For example, if the client has no permissions then the same message appears.
Closes #777
> fix: Error Message in SsiMiwOauth2ClientExtension updated

- charts/tractusx-connector-azure-vault/Chart.yaml
- charts/tractusx-connector-azure-vault/README.md
- charts/tractusx-connector/Chart.yaml
- charts/tractusx-connector/README.md
Update Postgres helm chart from 12.1.6 to 12.11.2
Because of a bug in current version 12.1.6
Closes #677
> chore: update postgresql helm chart from 12.1.6 to 12.11.2

- DEPENDENCIES
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/ClientErrorExceptionMapper.java
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/ConsumerAssetRequestController.java
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/test/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/model/ConsumerAssetRequestControllerTest.java
Adds `JSON` response when getting errors like:
- Not authorized
- EDR by TransferProcess ID not found
- EDR by Asset ID not found
- Multiple EDRs for Asset ID found
User experience
Closes #779
> feat(ConsumerProxy): enhances error response when fetching data

- DEPENDENCIES
- charts/tractusx-connector-azure-vault/templates/_helpers.tpl
- charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
- charts/tractusx-connector/templates/_helpers.tpl
- charts/tractusx-connector/templates/deployment-controlplane.yaml
- edc-controlplane/edc-controlplane-base/build.gradle.kts
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/Participant.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/TestRuntimeConfiguration.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractHttpProviderPushTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/HttpProviderPushInMemoryTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/HttpProviderPushInPostgresqlTest.java
- gradle/libs.versions.toml
adds  configuration and dependencies for control plane callback from the dataplane
consistency
Closes #781
> feat: adds CP callbacks for transfer complete/fail

- docs/development/postman/collection.json
Updates the examples in the postman collection to the v3 asset API.
The v2 API is deprecated.
Closes #744
> docs(postman): updated assets to v3

- DEPENDENCIES
- edc-extensions/edr/edr-cache-sql/README.md
- edc-extensions/edr/edr-cache-sql/src/main/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCache.java
- edc-extensions/edr/edr-cache-sql/src/main/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheExtension.java
- edc-extensions/edr/edr-cache-sql/src/test/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheTest.java
- edc-extensions/edr/edr-cache-sql/src/test/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheTransactionalTest.java
- edc-tests/e2e-tests/build.gradle.kts
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/PgHashicorpParticipantRuntime.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/PgParticipantRuntime.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/NegotiateEdrPostgresqlHashicorpVaultTest.java
- edc-tests/runtime/runtime-postgresql-hashicorp/README.md
- edc-tests/runtime/runtime-postgresql-hashicorp/build.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
Add the ability to configure a path in the vault for storing the EDRs
Flexibility
Closes #800
> feat(SqlEdrStore): add configurable vault path

- .github/actions/setup-java/action.yml
- .github/workflows/publish-docusaurus.yaml
- .github/workflows/publish-swaggerhub.yaml
- DEPENDENCIES
- resources/create_kit_documentation.sh
run `autodoc` on `publish-docusaurus` ci job to have the resulting `md` uploaded to docusaurus in the `Development View/05_EDC Extensions/` folder
documentation
- made `publish-swaggerhub` use the shared `setup-java` action step
- upgraded `setup-java` to `3.13.0`
- refactored `created_kit_documentation.sh`, extracting variables and wrapping paths with double quotes, to make the script less error prone
Closes #700
> docs: run autodoc and upload resulting md to docusaurus

- .github/workflows/publish.yaml
Add write permissions to the `publish-docusaurus` job
they are needed to run the job
Closes #809
> build: give permissions to Publish Artefacts

- .github/workflows/publish-new-release.yml
Fix release pipeline by removing `secret-presence` from the `publish-docusaurus` step
Release it's not working
> chore: removes secret-presence needs from publish release workflow

- .github/workflows/publish-swaggerhub.yaml
Sets the published version as default when it's a proper release (not snapshot)
documentation
Closes #819
> docs: set openapi default version on swaggerhub

- .github/workflows/publish.yaml
the `secrets: inherit` was removed for some reasons in https://github.com/eclipse-tractusx/tractusx-edc/commit/c8dd495469136af2c4db26856f5af2c9cf263f0c#diff-e81e13daadd1745de51d8b8d85fce1fcd9be355732b64d60a6b56e18c28388caL140
but as mentioned by the EF help desk, that setting is necessary:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3773#note_1223226 
fix publish to swaggerhub
> fix: add removed setting from publish workflow

- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/TestRuntimeConfiguration.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/DeleteEdrInMemoryTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/NegotiateEdrInMemoryTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/RenewalEdrInMemoryTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/proxy/DataPlaneProxyInMemoryTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractHttpConsumerPullWithProxyTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/HttpConsumerPullWithProxyInMemoryTest.java
- edc-tests/runtime/runtime-memory/build.gradle.kts
This test enables the DataEncryptor for all the in-mem tests
No reason not to have encryption
> feat: use encryption in all inmem tests

- edc-extensions/dataplane-proxy/edc-dataplane-proxy-provider-api/README.md
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-provider-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/provider/api/DataPlaneProxyProviderApiExtension.java
- edc-extensions/dataplane-proxy/edc-dataplane-proxy-provider-api/src/test/java/org/eclipse/tractusx/edc/dataplane/proxy/provider/api/response/DataPlaneProxyProviderApiExtensionTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/TestRuntimeConfiguration.java
Adds an optional setting to specify a jetty context into which to register the ProviderGatewayController.
[365](https://github.com/eclipse-tractusx/tractusx-edc/issues/365)
I don't know whether this is actually the correct approach.
Closes #365
> Feature: Add config parameter for ProviderGatewayController context registration

- DEPENDENCIES
- core/edr-core/build.gradle.kts
- edc-extensions/edr/edr-callback/src/main/java/org/eclipse/tractusx/edc/callback/TransferProcessLocalCallback.java
- edc-extensions/edr/edr-callback/src/test/java/org/eclipse/tractusx/edc/callback/TestFunctions.java
- edc-extensions/edr/edr-callback/src/test/java/org/eclipse/tractusx/edc/callback/TransferProcessLocalCallbackTest.java
- edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/api/MiwApiClientImpl.java
- edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/api/MiwClientException.java
- edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/api/MiwFallbackFactories.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/AbstractRenewalEdrTest.java
Handles `TransferProcessTerminated` event by transitioning the `refreshing` state into error  state. 
Additionally when an EDR gets renewed, the old transfer process will be marked as completed
error handling
Closes #837
> feat: handling renewals failure

- DEPENDENCIES
- charts/tractusx-connector-memory/templates/deployment-runtime.yaml
Replaces the deprecated WEB_HTTP_IDS_* with WEB_HTTP_PROTOCOL_*
see #875
Closes #875
> fix(helm): Replace deprecated WEB_HTTP_IDS_*

- .github/workflows/trivy.yml
- DEPENDENCIES
Use latest trivy-action v0.14.0 instead of master.
The trivy-actions are failing, it seems like there is a issue with master version
> fix: Failing trivy-actions to use the version v0.14.0

- CHANGELOG.md
Add the `0.5.2` and `0.5.3` changes to our static `CHANGELOG.md`
Keeping a complete history of our releases and changes on a single file
Closes #886
> chore: add 0.5.2 and 0.5.3 changes to CHANGELOG

- .github/workflows/deployment-test.yaml
Deactivates the deployment test for the Azure-Keyvault variant temporarily.
AZ Credentials are expired
.
> chore: deactivate azure tests temporarily

- SECURITY.md
This PR updates the `SECURITY.md` file to follow the most recent template
The new template explains usage of GitHub security advisories
Closes #888
> chore: use new SECURITY.md template

- NOTICE.md
- build.gradle.kts
- edc-controlplane/edc-controlplane-postgresql-azure-vault/notice.md
- edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/notice.md
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-runtime-memory/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-azure-vault/notice.md
- edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-hashicorp-vault/notice.md
- edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
This PR adds legal information about the OpenTelemetry Agent to the `notice.md` that we include with each Docker image.
In addition, the following legal documents are copied to the application root of the docker image: NOTICE.md, SECURITY.md, LICENSE, DEPENDENCIES
TRG 7.07
Closes #889
> chore: add legal info to Docker images

- .github/workflows/trivy.yml
Downgrade trivy action version to 0.12.0
The latest version had problems lately
> chore: downgrade trivy version

- .github/workflows/run-all-tests.yml
- .github/workflows/upgradeability-test.yaml
This PR adds an upgradeability test for our helm charts. to that end it:
- installs the last official release
- waits until both pods come up (DP and CP)
- installs the current (unreleased) version 
- waits until _that_ comes up
- executes `helm test`
TRG 5.09
Closes #887
> feat(test): add upgradeability test for Helm charts

- DEPENDENCIES
- charts/tractusx-connector-azure-vault/README.md
- charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
- charts/tractusx-connector-azure-vault/templates/deployment-dataplane.yaml
- charts/tractusx-connector-azure-vault/values.yaml
- charts/tractusx-connector/README.md
- charts/tractusx-connector/templates/deployment-controlplane.yaml
- charts/tractusx-connector/templates/deployment-dataplane.yaml
- charts/tractusx-connector/values.yaml
This PR allows for additional volume mounts in control plane and data plane.
In some situations, such as Secret providers delegating to a vault, this may come in handy.
> feat(helm): allow additional volume mounts

- core/edr-core/src/main/java/org/eclipse/tractusx/edc/edr/core/manager/EdrManagerImpl.java
- edc-extensions/edr/edr-callback/src/main/java/org/eclipse/tractusx/edc/callback/TransferProcessLocalCallback.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/Participant.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/AbstractRenewalEdrTest.java
As discussed in this PR #934 the correct state to transition when an EDR expire is `Terminated` and not `Completed` which aligns this with the `PolicyMonitor` behavior 
Consistency
> chore: Change the state of the transfer process when EDR expires to Teminated

- edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/contractdefinition/V0_0_8__Alter_ContractDefinition_Switch_Assets_Selector_Json.sql
Switch `assets_selector` type from `text` to `json`
permit queries over the assets selector properties
Closes #933
> feat: switch assets_selector type from text to json

- build.gradle.kts
- edc-controlplane/edc-controlplane-postgresql-azure-vault/notice.md
- edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/notice.md
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile
- edc-controlplane/edc-runtime-memory/notice.md
- edc-controlplane/edc-runtime-memory/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-azure-vault/notice.md
- edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile
- edc-dataplane/edc-dataplane-hashicorp-vault/notice.md
- edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
Upgrade to java 21
is the latest LTS version
> build(deps): bump eclipse-temurin base image to java 21

- core/edr-cache-core/src/main/java/org/eclipse/tractusx/edc/edr/core/EdrCacheCoreExtension.java
- edc-extensions/edr/edr-cache-sql/src/main/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheExtension.java
- edc-extensions/edr/edr-cache-sql/src/test/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheExtensionTest.java
Set EDR default data source name as `default`
permit to use the `default` fallback data source configuration
Closes #1009
> feat: set default EDR data source name as default

- docs/usage/management-api-walkthrough/02_policies.md
- docs/usage/management-api-walkthrough/07_edrs.md
- docs/usage/management-api-walkthrough/08_contractagreements.md
Changes the ODRL payloads from uppercase `USE` to lowercase `use`.
As discussed [in another PR](https://github.com/eclipse-tractusx/tractusx-edc/pull/856#discussion_r1470715576), ODRL is case-sensitive. To [follow the standard](https://w3c.github.io/odrl/bp/#x1-how-to-represent-a-general-permission), use the lowercase `use`.
./.
> docs: fix action use in ODRL payloads

- DEPENDENCIES
- edc-extensions/transferprocess-sftp-client/build.gradle.kts
- edc-extensions/transferprocess-sftp-common/build.gradle.kts
- edc-extensions/transferprocess-sftp-provisioner/build.gradle.kts
- gradle/libs.versions.toml
Removes unused mockito-inline dependency
cleanup
Closes #1025
> refactor: remove unused mockito-inline dependency

- edc-extensions/postgresql-migration/build.gradle.kts
- edc-extensions/postgresql-migration/src/main/java/org/eclipse/tractusx/edc/postgresql/migration/AbstractPostgresqlMigrationExtension.java
- edc-extensions/postgresql-migration/src/main/java/org/eclipse/tractusx/edc/postgresql/migration/FlywayManager.java
- edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/asset/V0_0_6__Transform_Property_Array_To_Map.sql
- edc-extensions/postgresql-migration/src/test/java/org/eclipse/tractusx/edc/postgresql/migration/AssetPostgresqlMigrationExtensionTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/AbstractDeleteEdrTest.java
- gradle/libs.versions.toml
Add migration to transform sql asset json properties from array to map.
fix bug
- Extracted a `FlywayManager` class that takes care of create the flyway config and execute it, that can be used by both tests and production code
- put flyway dependency version in version catalog
- sorted "versions" and "other deps" sections of the version catalog alphabetically (sorry, couldn't resist :hand_over_mouth: )
Closes #1003
> fix: migrate asset json properties from array to map

- .github/workflows/trivy.yml
Reverts eclipse-tractusx/tractusx-edc#1031
Seems that 0.17.0 has some issue
https://github.com/eclipse-tractusx/tractusx-edc/actions/runs/7828940383
> Revert "chore(deps): bump aquasecurity/trivy-action from 0.12.0 to 0.17.0"

- core/json-ld-core/src/test/java/org/eclipse/tractusx/edc/jsonld/JsonLdExtensionTest.java
- edc-controlplane/edc-runtime-memory/src/test/java/org/eclipse/tractusx/edc/vault/memory/VaultSeedExtensionTest.java
- edc-extensions/data-encryption/src/test/java/org/eclipse/tractusx/edc/data/encryption/TxEncryptorExtensionTest.java
- edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/EdrApiExtensionTest.java
- edc-extensions/edr/edr-callback/src/test/java/org/eclipse/tractusx/edc/callback/InProcessCallbackRegistryExtensionTest.java
- edc-extensions/edr/edr-callback/src/test/java/org/eclipse/tractusx/edc/callback/LocalCallbackExtensionTest.java
- edc-extensions/ssi/ssi-identity-core/src/test/java/org/eclipse/tractusx/edc/iam/ssi/identity/SsiIdentityServiceExtensionTest.java
- edc-extensions/ssi/ssi-identity-extractor/src/test/java/org/eclipse/tractusx/edc/iam/ssi/identity/extractor/SsiIdentityExtractorExtensionTest.java
- edc-extensions/ssi/ssi-miw-credential-client/src/test/java/org/eclipse/tractusx/edc/iam/ssi/miw/SsiMiwApiClientExtensionTest.java
- edc-extensions/ssi/ssi-miw-credential-client/src/test/java/org/eclipse/tractusx/edc/iam/ssi/miw/SsiMiwConfigurationExtensionTest.java
- edc-extensions/ssi/ssi-miw-credential-client/src/test/java/org/eclipse/tractusx/edc/iam/ssi/miw/SsiMiwCredentialClientExtensionTest.java
- edc-extensions/ssi/ssi-miw-credential-client/src/test/java/org/eclipse/tractusx/edc/iam/ssi/miw/SsiMiwOauth2ClientExtensionTest.java
- edc-extensions/ssi/ssi-miw-credential-client/src/test/java/org/eclipse/tractusx/edc/iam/ssi/miw/SsiMiwValidationRuleExtensionTest.java
This PR introduces a refactorization of service extesion tests to remove unecessary instantiations of the ServiceExtensionContext and ObjectFactory.
Refactor.
Closes #972
> refactor(tests): Tests use ServiceExtensionContext injection

- resources/hashtag.header
- resources/java.header
This PR changes the Checkstyle slightly. Previously it required the license header to be wrapped in 
multi-line comments, with a leading and trailing line of 80 `"*"` characters.
This has been reduced to require only a valid multi-line comment.
IntelliJ has a feature to automatically add license headers, but it can't add the asterisk-line, which would cause
it to generate invalid license headers.
> chore: make license header regex more permissive

- DEPENDENCIES
- edc-controlplane/edc-controlplane-base/build.gradle.kts
- edc-dataplane/edc-dataplane-base/build.gradle.kts
- edc-extensions/auth-tokenbased/README.md
- edc-extensions/auth-tokenbased/build.gradle.kts
- edc-extensions/auth-tokenbased/src/main/java/org/eclipse/tractusx/edc/api/auth/token/TokenBasedAuthenticationExtension.java
- edc-extensions/auth-tokenbased/src/main/java/org/eclipse/tractusx/edc/api/auth/token/TokenBasedAuthenticationService.java
- edc-extensions/auth-tokenbased/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
- edc-extensions/auth-tokenbased/src/test/java/org/eclipse/tractusx/edc/api/auth/token/TokenBasedAuthenticationExtensionTest.java
- edc-extensions/auth-tokenbased/src/test/java/org/eclipse/tractusx/edc/api/auth/token/TokenBasedAuthenticationServiceTest.java
- edc-tests/edc-dataplane-proxy-e2e/build.gradle.kts
- gradle/libs.versions.toml
- settings.gradle.kts
Backport of https://github.com/eclipse-edc/Connector/pull/3607 in 0.5.x
> chore: backport of issue upstream#3607

- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/common/AbstractDynamicConstraintFunction.java
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/common/CredentialTypePredicate.java
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/dismantler/DismantlerConstraintFunction.java
- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementConstraintFunction.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/CredentialFunctions.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/dismantler/DismantlerConstraintFunctionTest.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementConstraintFunctionTest.java
This PR adds a Dismantler constraint evaluation function.
Support for all required Tractus-X policy constraints
- even though the spec only requires that `activityType` is a String, this evaluation function also supports it being a list-type.
- introduces a base class for dynamic constraint functions to share common functionality
> feat: add Dismantler constraint eval function

- charts/tractusx-connector-memory/templates/deployment-runtime.yaml
- charts/tractusx-connector-memory/values.yaml
- edc-controlplane/edc-runtime-memory/README.md
- edc-controlplane/edc-runtime-memory/src/main/docker/Dockerfile
Removes the rewrite of ENV variable "SECRETS" to edc.vault.secrets and instead uses the EDC_VAULT_SECRETS directly in the memory chart and Dockerfile.
With the current setup, this is the only ENV variable, that is rewritten. While checking the documentation of the edc components, this rewrite is not apparent. In short: I don't see any reason for it, except potential confusion.
Also fixes the documentation regarding the seeding of secrets with semicolon separated k:v list
Closes #1039
> improvement(memory-edc): remove EDC_VAULT_SECRETS rewrite

- .github/actions/setup-memory-runtime/action.yml
- .github/workflows/dast-scan.yaml
- DEPENDENCIES
- dast/docker-compose.yaml
- dast/fetch-token.sh
Integrates DAST workflow for
- ZAP API scan
- ZAP FULL scan
- Custom authenticated requests
Q-Gate
> feat: dast scan integration

- docs/development/decision-records/2024-03-05_token_refresh/README.md
Adds a Decision Record for token refresh based on:
https://github.com/eclipse-tractusx/tractusx-profiles/blob/main/tx/refresh/refresh.token.grant.profile.md
Closes #1105
> feat: Add Decision Record for token refresh

- .github/workflows/upgradeability-test.yaml
- DEPENDENCIES
- edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/EdrApiTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/tx/iatp/DataspaceIssuer.java
Fixes IATP tests
build failing
> chore: fixes after upstream changes

- DEPENDENCIES
- edc-dataplane/edc-dataplane-base/build.gradle.kts
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-api/build.gradle.kts
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-api/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/api/TokenRefreshApiExtension.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-api/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/api/v1/TokenRefreshApi.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-api/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/api/v1/TokenRefreshApiController.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-api/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-api/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/api/v1/TokenRefreshApiControllerTest.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceExtension.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImpl.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImplComponentTest.java
- edc-tests/edc-dataplane/edc-dataplane-tokenrefresh-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/e2e/DataPlaneTokenRefreshEndToEndTest.java
- edc-tests/edc-dataplane/edc-dataplane-tokenrefresh-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/e2e/RuntimeConfig.java
- gradle/libs.versions.toml
- settings.gradle.kts
This PR adds the Refresh API to the dataplane, effectively exposing the possibility to refresh dataplane access tokens.
The Refresh API is registered into th `"public"` context, thus it is available under `POST <HOST>:<PUBLIC_API_PORT>/<PUBLIC_API_PATH>/v1/token`. 
Using all defaults, that is:
```
POST http://localhost:8185/api/v1/public/token
```
or - using the v2 endpoint:
```
POST http://localhost:8185/api/v2/public/token
```
using the V2 endpoint is **highly encouraged** as the V1 endpoint will not use data plane signaling, access tokens or token refresh!
Short-lived tokens are a security best-practice
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method signature changes, package declarations, bugs that were encountered …
> feat: add Token RefreshAPI to data plane

- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceExtension.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImpl.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImplComponentTest.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImplTest.java
This PR adds a check for token expiry to the `DataPlaneTokenRefreshService` to reject resolving expired access tokens.
the `resolve()` method is called during authorization of a HTTP pull request against the dataplane, so in Tractus-X EDC it needs to reject expired access tokens.
> fix: add expiry check to DataPlaneTokenRefreshServiceImpl

- DEPENDENCIES
- docs/usage/management-api-walkthrough/02_policies.md
Add new policy description to tractusx-edc
There are many policy descriptions scattered around. The aim is to have a description that describes everything you need to know about policies in Catena-X. The destination of this description should be the tractusx-edc repository.
Closes #701
> doc(policies): add policy description in tractusx-edc

- DEPENDENCIES
- edc-extensions/edr/edr-cache-sql/src/test/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheTest.java
- edc-extensions/edr/edr-cache-sql/src/test/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCacheTransactionalTest.java
- edc-extensions/iatp/tx-iatp-sts-dim/src/main/java/org/eclipse/tractusx/edc/iam/iatp/sts/dim/DimSecureTokenService.java
- edc-extensions/iatp/tx-iatp-sts-dim/src/test/java/org/eclipse/tractusx/edc/iam/iatp/sts/dim/DimSecureTokenServiceTest.java
- edc-extensions/postgresql-migration/src/test/java/org/eclipse/tractusx/edc/postgresql/migration/AssetPostgresqlMigrationExtensionTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/catalog/CatalogPostgresqlTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/DeleteEdrPostgresqlTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/NegotiateEdrPostgresqlHashicorpVaultTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/NegotiateEdrPostgresqlTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/edr/RenewalEdrPostgresqlTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/policy/PolicyMonitorPostgresqlTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/proxy/DataPlaneProxyPostgresqlTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/HttpConsumerPullWithProxyPostgresqlTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/HttpProviderPushInPostgresqlTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/token/DimDispatcher.java
fix with the latest EDC/IH changes
fix compile errors and tests
> chore: fix with the latest EDC/IH changes

- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/EdrApiExtension.java
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/dto/NegotiateEdrRequestDto.java
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/schema/EdrSchema.java
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/transform/JsonObjectToNegotiateEdrRequestDtoTransformer.java
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/transform/NegotiateEdrRequestDtoToNegotiatedEdrRequestTransformer.java
- edc-extensions/edr/edr-api/src/main/java/org/eclipse/tractusx/edc/api/edr/validation/NegotiateEdrRequestDtoValidator.java
- edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/EdrApiTest.java
- edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/TestFunctions.java
- edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/transform/JsonObjectToNegotiateEdrRequestDtoTransformerTest.java
- edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/transform/NegotiateEdrRequestDtoToNegotiateEdrRequestTransformerTest.java
- edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/validation/NegotiateEdrRequestDtoValidatorTest.java
Changes `NegotiateEDRRequestDto` to use only `Policy` instead of `Offer`.
Remove duplicate data in the api.
Changes are similar to [3395](https://github.com/eclipse-edc/Connector/issues/3395) Upsteam.
Closes #936
> feature(api): Update NegotiateEdrRequestDto

- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceExtension.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImpl.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImplComponentTest.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImplTest.java
When validating the access token resolve the key id with the `LocalPublicKeyService`
Closes #1161
> fix: use LocalPublicKeyService for data plane token verification

- edc-extensions/iatp/tx-iatp/build.gradle.kts
- edc-extensions/iatp/tx-iatp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/IatpScopeExtractorExtension.java
- edc-extensions/iatp/tx-iatp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/scope/CredentialScopeExtractor.java
- edc-extensions/iatp/tx-iatp/src/test/java/org/eclipse/tractusx/edc/iam/iatp/scope/CredentialScopeExtractorTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/helpers/DimHelper.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/DimParticipant.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/catalog/DimCatalogIntegrationTest.java
- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/DimHttpPullTransferIntegrationTest.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/transfer/HttpConsumerPullBaseTest.java
- edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractIatpConsumerPullTest.java
- edc-tests/runtime/iatp/runtime-memory-iatp-dim-ih/build.gradle.kts
Runs the policy extractor only on those messages Egress/Ingress:
- CatalogRequestMessage
- ContractRequestMessage
- TransferRequestMessage
that are the messages where the policy evaluation is done in the provider side and needs to be working with the required credentials (from policy).
In addition in this PR
- Restored IATP tests with policy combination 
- Adapted DIM integration test to use a mocked version of BDRS server
Closes #1175
> feat: extract scopes only on relevant messages

- edc-controlplane/edc-controlplane-base/build.gradle.kts
- edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientAudienceMapper.java
- edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientExtension.java
- edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImpl.java
- edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientMapperExtension.java
- edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientAudienceMapperTest.java
- edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImplExtensionTest.java
- edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImplTest.java
- edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientMapperExtensionTest.java
- edc-extensions/data-flow-properties-provider/build.gradle.kts
- edc-extensions/data-flow-properties-provider/src/main/java/org/eclipse/tractusx/edc/flow/TxDataFlowPropertiesProvider.java
- edc-extensions/data-flow-properties-provider/src/main/java/org/eclipse/tractusx/edc/flow/TxDataFlowPropertiesProviderExtension.java
- edc-extensions/data-flow-properties-provider/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
- edc-extensions/data-flow-properties-provider/src/test/java/org/eclipse/tractusx/edc/flow/TxDataFlowPropertiesProviderExtensionTest.java
- edc-extensions/data-flow-properties-provider/src/test/java/org/eclipse/tractusx/edc/flow/TxDataFlowPropertiesProviderTest.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceImpl.java
- edc-tests/edc-controlplane/fixtures/build.gradle.kts
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/BeforeInitCallback.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/ParticipantRuntime.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/Runtimes.java
- edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/runtime/IatpParticipantRuntime.java
- edc-tests/edc-controlplane/transfer-tests/build.gradle.kts
- edc-tests/edc-controlplane/transfer-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/TransferWithTokenRefreshTest.java
- settings.gradle.kts
- spi/bdrs-client-spi/build.gradle.kts
- spi/bdrs-client-spi/src/main/java/org/eclipse/tractusx/edc/spi/identity/mapper/BdrsClient.java
Inject the audience(DID) as additional property in the `DataFlowStartMessage` for later verification in refresh token.
The DID is resolved via implementation of `BdrsClient`
- The `BdrsClient` has been renamed to `BdrsClientImpl` and an SPI `BdrsClient` was introduced.
- The integration with the `AudienceMapper` now it's done in `BdrsClientAudienceMapper`
- In the custom `DataFlowPropertiesProvider` the `BdrsClient` is injected for resolving BPN -> DID and setting the additional property `audience` for token renewal checks 
- The `ParticipantRuntime` has been enriched for injecting custom mock services directly from the tests (Runtime creation)
_List other areas of code that have changed but are not necessarily linked to the main feature. This …
> feat: inject the audience(DID) as additional property

- .github/release.yaml
- DEPENDENCIES
Improves the categorization of issues in automatically generated release notes. This new config matches the one we have in upstream EDC.
Avoid bloated and hard-to-read release notes
> chore: improve github release config

- edc-extensions/dataplane/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/ConsumerAssetRequestController.java
- edc-extensions/dataplane/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/test/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/model/ConsumerAssetRequestControllerTest.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/ParticipantConsumerDataPlaneApi.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/transfer/HttpConsumerPullBaseTest.java
Fixes fetching data when providing additional `providerId` property as  filtering
bugfix
Closes #1202
> fix: typo in providedId filter mapping

- DEPENDENCIES
- core/core-utils/src/main/java/org/eclipse/tractusx/edc/core/utils/RequiredConfigWarnings.java
- edc-extensions/bdrs-client/build.gradle.kts
- edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientExtension.java
- edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImpl.java
- edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImplExtensionTest.java
- edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImplTest.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/DataPlaneTokenRefreshServiceExtension.java
- edc-extensions/iatp/tx-iatp-sts-dim/src/main/java/org/eclipse/tractusx/edc/iam/iatp/sts/dim/DimSecureTokenServiceExtension.java
- edc-extensions/iatp/tx-iatp-sts-dim/src/main/java/org/eclipse/tractusx/edc/iam/iatp/sts/dim/DimStsConfigurationExtension.java
- edc-extensions/iatp/tx-iatp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/IatpDefaultScopeExtension.java
- edc-extensions/iatp/tx-iatp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/scope/CredentialScopeExtractor.java
- edc-extensions/iatp/tx-iatp/src/test/java/org/eclipse/tractusx/edc/iam/iatp/IatpDefaultScopeExtensionTest.java
- edc-extensions/iatp/tx-iatp/src/test/java/org/eclipse/tractusx/edc/iam/iatp/scope/CredentialScopeExtractorTest.java
- edc-extensions/tokenrefresh-handler/src/main/java/org/eclipse/tractusx/edc/common/tokenrefresh/TokenRefreshHandlerExtension.java
- gradle/libs.versions.toml
- samples/multi-tenancy/build.gradle.kts
- spi/bdrs-client-spi/build.gradle.kts
- spi/core-spi/src/main/java/org/eclipse/tractusx/edc/TxIatpConstants.java
adds a VerifiablePresentation containing the `MembershipCredential` to the `Authorization` header of a BDRS request.
Specifically, assuming we're using JWT-VPs, this will add a header:
```
"Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6I...."
```
In order to do that, the `BdrsClient` requires access to the `SecureTokenService` to create a self-issued ID token.
That SI token is then used to execute a `PresentationQuery` request to `CredentialService`, we "IATP ourselves".
The CredentialService's URL is resolved via a config parameter, and as a fallback, is resolved from the DID document.
Securing the directory API of the BDRS server.
A similar PR will come for the BDRS Server, to verify the auth header.
> feat: add Authorization header to BDRS request

- docs/development/decision-records/2024-04-11_txedc_release_train/README.md
Adds a decision record about more frequent txedc releases.
release early, release often
> docs: add Decision-Record about txedc release train

- .github/workflows/verify.yaml
- docs/development/decision-records/2024-04-11_remove_sftp/README.md
Adds a decision record about removing SFTP.
documenting the decision
> docs: add Decision-Record about removing SFTP extensions

- edc-extensions/provision-additional-headers/src/main/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersProvisioner.java
- edc-extensions/provision-additional-headers/src/test/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersProvisionerTest.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/ParticipantDataApi.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/ParticipantEdrApi.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java
- edc-tests/edc-controlplane/transfer-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/TransferPullEndToEndTest.java
- edc-tests/edc-controlplane/transfer-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/TransferWithTokenRefreshTest.java
Adds two tests for transfer in the following transfer process states:
- STARTED -> SUSPENDED -> STARTED (suspension)
- STARTED  -> TERMINATED ->  (contract expires)
Additionally fixed the `AdditionalHeadersProvisioner` which had some issue with the deprovision phase
testing is good.
> feat: adds transfer tests with suspend/resume and terminate scenario

- core/json-ld-core/src/main/java/org/eclipse/tractusx/edc/jsonld/JsonLdExtension.java
- core/json-ld-core/src/main/resources/document/tx-auth-v1.jsonld
- core/json-ld-core/src/main/resources/document/tx-v1.jsonld
create additional JSON-LD context for the `tx` and `tx-auth` namespace
> The tx one already existed but it was clean up from the old policy term definitions with now are in the `cx-policy` namespace
policy definition usability
Closes #1233
> feat: add additional tx JSON-LD contexts

- DEPENDENCIES
- docs/usage/management-api-walkthrough/02_policies.md
- docs/usage/management-api-walkthrough/04_catalog.md
- docs/usage/management-api-walkthrough/05_contractnegotiations.md
- docs/usage/management-api-walkthrough/06_transferprocesses.md
- docs/usage/management-api-walkthrough/08_contractagreements.md
updates the walkthrough mostly by adjusting payloads and adding 0.7.x relevant documentation
documentation
Closes #1239
> docs: update walkthrough guide

- DEPENDENCIES
- docs/usage/management-api-walkthrough/01_assets.md
- docs/usage/management-api-walkthrough/02_policies.md
- docs/usage/management-api-walkthrough/03_contractdefinitions.md
- docs/usage/management-api-walkthrough/04_catalog.md
- docs/usage/management-api-walkthrough/05_contractnegotiations.md
- docs/usage/management-api-walkthrough/06_transferprocesses.md
- docs/usage/management-api-walkthrough/07_edrs.md
- docs/usage/management-api-walkthrough/08_contractagreements.md
- docs/usage/management-api-walkthrough/README.md
This is a partial update to the [Management API Walkthrough](docs/usage/management-api-walkthrough) with focus on the payloads and consistency.
Not considered for now:
- [01_assets.md](docs/usage/management-api-walkthrough/01_assets.md) > HTTP Data Plane
- [02_policies.md](docs/usage/management-api-walkthrough/02_policies.md) > Testing SSI interactions
- dct namespace changes (https://github.com/eclipse-edc/Connector/pull/3914)
- Callbacks
- EDR resolution
> Update management api walkthrough

- DEPENDENCIES
- docs/migration/Version_0.5.x_0.7.x.md
Adds a Migration Guide for moving toward Tractus-X EDC 0.7.x
.
Closes #1222
> chore: add migration guide for 0.7.x

- edc-tests/runtime/mock-connector/notice.md
Adds the `notice.md` file to the docker build of the Mock Connector
It was missing, causing the build to fail.
> fix: add notice file to Mock Connector

- edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/CredentialSpoofTest.java
- edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/IatpParticipants.java
adds two tests on those spoofing scenario:
- Malicious actor try to impersonate a consumer by creating a presentation with the  consumer membership credential
- Malicious actor try to impersonate a consumer sending in the presentation query response a valid consumer VP with membership credential
> chore: add more iatp tests 

- edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/catalog/DimCatalogIntegrationTest.java
disable DIM int test
currenty try to run it in the `verify-dim` workflow but it fails for missing configuration. For now we just comment it as `@Test` till we decide to configure it or delete it 
> chore: disable dim int test

- edc-extensions/edr/edr-api-v2/src/main/java/org/eclipse/tractusx/edc/api/edr/v2/EdrCacheApi.java
- edc-extensions/edr/edr-api-v2/src/main/java/org/eclipse/tractusx/edc/api/edr/v2/EdrCacheApiController.java
- edc-extensions/edr/edr-api-v2/src/test/java/org/eclipse/tractusx/edc/api/edr/v2/EdrCacheApiControllerTest.java
makes the `auto_refresh` query param of the EDR API `true` by default.
not refreshing should be intended behaviour, not the default.
> feat: make auto_refresh default to true

- charts/tractusx-connector-azure-vault/README.md
- charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
- charts/tractusx-connector-azure-vault/templates/deployment-dataplane.yaml
- charts/tractusx-connector-azure-vault/values.yaml
Make Azure Vault related variables optional in deployment chart.
While deploying EDC using "tractusx-connector-azure-vault" on Azure utilizing workload identity, charts are overriding the values that are attached automatically by Azure webhook.
n/a
Closes #1304
> fix: make azure vault related variables in deployment chart optional #1304

- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/main/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/rules/AuthTokenAudienceRule.java
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-core/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/core/rules/AuthTokenAudienceRuleTest.java
- edc-tests/edc-dataplane/edc-dataplane-tokenrefresh-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/e2e/DataPlaneTokenRefreshEndToEndTest.java
adds checks on `accessTokenData` not found in `AuthTokenAudienceRule`
NPE fix
Closes #1303
> fix: adds checks on accessTokenData not found

- .github/dependabot.yml
- DEPENDENCIES
- edc-controlplane/edc-runtime-memory/src/main/docker/Dockerfile
- edc-tests/runtime/mock-connector/src/main/docker/Dockerfile
- samples/edc-dast/edc-dast-runtime/src/main/docker/Dockerfile
Align eclipse-temurin versions to `22.0.1_8-jre-alpine` on all the dockerfiles.
Updated dependabot.yml to make it take care of keeping them aligned.
version updates
> build(deps): align eclipse-temurin versions to 22.0.1_8-jre-alpine

- .github/actions/run-deployment-test/action.yml
- .github/workflows/deployment-test.yaml
Converts the deployment test to a matrix test running against the last three kubernetes versions
TRG 5.10
Closes #1313
> feat(ci): add multi-k8s versions test

- .github/workflows/publish-swaggerhub.yaml
Update upstream openapi spec urls to the latest format.
keep dependencies updated
Closes #1316
> docs: switch upstream openapi spec fetch from SH to GP

- charts/tractusx-connector-azure-vault/README.md
- charts/tractusx-connector-azure-vault/values.yaml
- charts/tractusx-connector-memory/README.md
- charts/tractusx-connector-memory/values.yaml
- charts/tractusx-connector/README.md
- charts/tractusx-connector/values.yaml
- edc-tests/deployment/src/main/resources/helm/tractusx-connector-azure-vault-test.yaml
- edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml
removes  `transferProxyTokenEncryptionAesKey` setting
cleanup, not used in 0.7.x
Closes #1270
> chore: removes  transferProxyTokenEncryptionAesKey setting

- docs/usage/management-api-walkthrough/07_edrs.md
fixes url in EDR walkthrough
documentation
Closes #1315
> chore: fixes url in EDR walkthrough

- .github/workflows/publish-context.yaml
publish tractusx-edc custom JSON-LD context for:
- Base tx-edc  BusinessPartnerNumber and BusinessPartnerGroup terms
- Auth context: EDC extension for token renewal support in DPS
dev experience
> chore: publish tractusx-edc custom JSON-LD context

- .github/workflows/verify.yaml
- DEPENDENCIES
- edc-tests/edc-dataplane/cloud-transfer-tests/build.gradle.kts
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzureBlobHelper.java
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzureToAzureTest.java
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/CloudTransferTest.java
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/MultiCloudTest.java
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/S3ToS3Test.java
- gradle/libs.versions.toml
Removes `aws-s3-test` and `azure-test` dependencies
not really necessary: 
- the annotations have been replaced by a single, more understandable `CloudTransferTest`
- the call to a test fixture methods has been inlined
Closes #1368
> refactor(test): cleanup unneeded dependencies

- .github/workflows/draft-new-release.yaml
- .tractusx
Adds `openApiSpecs` link in `.tractusx` metadata fiile
documentation
- ensured that on every version release the version number will be bumped
Closes #1384
> docs: add openapi spec link to metadata file

- DEPENDENCIES
- edc-extensions/migrations/control-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/contractnegotiation/V0_0_9__Alter_ContractNegotiation_CreateStateIndex.sql
- edc-extensions/migrations/control-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/policy-monitor/V0_0_2__Alter_PolicyMonitor_CreateStateIndex.sql
- edc-extensions/migrations/control-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/transferprocess/V0_0_16__Alter_TransferProcess_CreateStateIndex.sql
- edc-extensions/migrations/data-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/dataplane/V0_0_2__Alter_Dataplane_AddTransferTypeDestinationColumn.sql
- edc-extensions/migrations/data-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/dataplane/V0_0_3__Alter_Dataplane_CreateStateIndex.sql
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzureToAzureTest.java
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/MultiCloudTest.java
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/S3ToS3Test.java
- edc-tests/edc-dataplane/edc-dataplane-tokenrefresh-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/tokenrefresh/e2e/DataPlaneTokenRefreshEndToEndTest.java
- gradle/libs.versions.toml
optimize state machines with index on state and state_timestamp
Closes #1394
> feat: optimize state machines

- .github/workflows/publish-swaggerhub.yaml
Get latest upstream openapi specs before merging and publishing
currently they are not included because api version diverged from library version
- this is a quick patch waiting for the specs to be included as artifacts, after then, the full spec will be built by merging the ones from the modules that are part of the build
Closes #1393
> docs(api): fix published api specs

- edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractIatpConsumerPullTest.java
- edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/harness/IatpHelperFunctions.java
add test on Data Exchange Governance use case
Closes #1400
> feat: add test on Data Exchange Governance use case

- docs/development/bidirectional-transfer/BidirectionalDataTransfer.md
Adds a concept for Bidirectional Data Transfers. Associated with this [issue](https://github.com/eclipse-tractusx/sig-release/issues/624).
Closes #1397
> doc: Add concept document for Bidirectional Data Transfer

- DEPENDENCIES
- build.gradle.kts
just a fix for the previous PR about openapi documentation (#1402 )
Part of #1393
> build(fix): register downloadOpenapi for all subprojects

- .github/workflows/publish-openapi-ui.yml
Add workflow that  builds and publish openapi-ui on github pages
Closes #1409
> docs: publish openapi-ui to github pages

- docs/development/decision-records/2024-07-18-Improvements-versioning-scheme/README.md
Adds a decision record outlining changes to the versioning scheme and release cadence.
documentation, transparency
> docs: decisio-record abour versioning scheme

- .github/workflows/publish-openapi-ui.yml
- .github/workflows/publish-swaggerhub.yaml
- edc-extensions/bpn-validation/bpn-validation-api/build.gradle.kts
- edc-extensions/dataplane/dataplane-proxy/edc-dataplane-proxy-consumer-api/build.gradle.kts
- edc-extensions/dataplane/dataplane-token-refresh/token-refresh-api/build.gradle.kts
- edc-extensions/edr/edr-api-v2/build.gradle.kts
- edc-tests/runtime/mock-connector/build.gradle.kts
- gradle/libs.versions.toml
Split openapi documentation in `control-plane` and `data-plane` 
documentation
Part of  #1409
> docs: split openapi spec by plane

- DEPENDENCIES
- charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
- charts/tractusx-connector/templates/deployment-controlplane.yaml
- edc-extensions/migrations/control-plane-migration/src/main/java/org/eclipse/tractusx/edc/postgresql/migration/FederatedCatalogCacheMigrationExtension.java
- edc-extensions/migrations/control-plane-migration/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
- edc-extensions/migrations/control-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/federatedcatalog/V0_0_1__Init_FederatedCatalogCache_Database_Schema.sql
- edc-tests/edc-controlplane/catalog-tests/src/test/java/org/eclipse/tractusx/edc/tests/catalog/FederatedCatalogTest.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/PgRuntimeExtension.java
- gradle/libs.versions.toml
enable federated catalog cache SQL variant
Closes #1429
> feat: enable federated catalog cache SQL variant

- DEPENDENCIES
- charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
- charts/tractusx-connector-azure-vault/templates/deployment-dataplane.yaml
- charts/tractusx-connector-memory/templates/deployment-runtime.yaml
- charts/tractusx-connector/templates/deployment-controlplane.yaml
- charts/tractusx-connector/templates/deployment-dataplane.yaml
Makes the DIM url Helm value optional to enable the switch to the regular STS client
Closes #1443
> fix(charts): make DIM URL optional

- .github/workflows/publish-new-release.yml
- .github/workflows/publish-new-snapshot.yaml
- .github/workflows/trigger-maven-publish.yaml
`publish-new-release.yaml` and `publish-new-snapshot.yaml` invoke the `trigger-[maven|docker]-publish.yaml` workflow to increase code re-use.
avoid duplication
- `publish.yaml` was renamed `publish-new-snapshot.yaml`
- successful(-ish) workflow run in my [fork](https://github.com/paullatzelsperger/tractusx-edc/actions/runs/10059604679)
Closes #1447
> feat(ci): publish workflows call reusable trigger workflows

- .github/actions/publish-docker-image/action.yml
- build.gradle.kts
copy dockerfile into `build/resources/docker`
avoid conflicts with `jar` task
> build: change copyDockerfile output path

- .github/workflows/publish-new-release.yml
- .github/workflows/publish-new-snapshot.yaml
- .github/workflows/publish-openapi-ui.yml
- .github/workflows/run-all-tests.yml
- .github/workflows/trigger-docker-publish.yaml
- .github/workflows/trigger-maven-publish.yaml
Enables intermediate builds (weekly, on Monday at 03:00 AM UTC). More specifically, the following changes were made:
- `trigger-{maven|docker}-publish.yaml`: added log lines to print the input parameters
- `publish-new-snapshot.yaml`
- added a job to determine the version using a date string, if the parent workflow (`run-all-tests`) was triggered by a `schedule` event
- added a job to publish OpenAPI specs to GH Pages
- supply that version to the publish maven, docker and openapi jobs
- `publish-new-release.yaml`: added a job to publish OpenAPI specs to GH Pages
intermediate builds shorten dev adoption and feedback loops
_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method signature changes, package declarations, bugs that …
> feat(ci): add periodic build trigger

- .github/workflows/publish-openapi-ui.yml
This should fix the broken deploy of swagger ui:
https://github.com/eclipse-tractusx/tractusx-edc/actions/runs/10078713965/job/27864470198
> build: add write contents permission to deploy-swagger-ui

- DEPENDENCIES
- edc-extensions/dataplane/dataplane-selector-configuration/build.gradle.kts
- edc-extensions/migrations/control-plane-migration/build.gradle.kts
- edc-extensions/migrations/data-plane-migration/build.gradle.kts
- edc-extensions/migrations/postgresql-migration-lib/build.gradle.kts
Fix dependency scope for `libs.edc.junit`
Closes #1462
> build: fix dependency scope for libs.edc.junit

- .github/workflows/trigger-docker-publish.yaml
removes obsolete `do_push` parameter, that was previously removed from the called workflow
> fix(ci): remove obsolete workflow parameter `do_push`

- DEPENDENCIES
- gradle/libs.versions.toml
bumps to the latest EDC nightly in preparation for a `0.8.0-rc2` release
> chore(deps): bump to latest EDC nightly

- .github/workflows/dash-scan.yml
- .github/workflows/secrets-scan.yml
- .github/workflows/verify.yaml
TruffleHog is the OSS replacement for GitGuardian that will be replaced soon.
Details: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/950
- removed "verify license header" job because it's already done by checkstyle
> build: TRG-8-03 enable TruffleHog secrets scan

- edc-extensions/bpn-validation/bpn-validation-core/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/BusinessPartnerGroupFunction.java
- edc-extensions/bpn-validation/bpn-validation-core/src/test/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/BusinessPartnerGroupFunctionTest.java
- Fixed **IS_ALL_OF** operator validation. It had the same behavior of **EQ** operator
- Fixed **IS_NONE_OF** operator validation. It had the same behavior of the **NEQ** operator
- Fixed **NEQ** operator validation. It was considering the opposite result of the IN operator, and it should be the opposite of the EQ operator
- Added a new rule when the BPN groups or assigned groups are empty, and if the operator is **NEQ** or **IS_NONE_OF**, it returns true instead of false
In order to keep the correct behavior on BPNL validations
Some minor adjusts reported by Sonar, including:
- Adjusted String format and casting
Closes #https://github.com/eclipse-tractusx/tractusx-edc/issues/1411
Closes #https://github.com/eclipse-tractusx/tractusx-edc/issues/775
> Fix: Adjusted BPN validations on different operators

- .github/workflows/publish-new-release.yml
- .github/workflows/trigger-docker-publish.yaml
- DEPENDENCIES
changes the value of the `docker_tag` input to use the step output of the version extraction step. also fixes a log line
> fix(ci): use RELEASE_VERSION from step output

- .github/workflows/publish-swaggerhub.yaml
Cherry-pick of that commit to include the correct upstream specs during publishing in SwaggerHub.
> docs(api): fix published api specs (#1399)

- .github/workflows/publish-bugfix-release.yml
Brings in the temporary publish-bugfix workflow to main from the bugfix/0.7.4 branch.
This is needed for the workflow to be executed manually from the Actions tab.
> chore(workflows): Add publish-bugfix-release workflow to main

- DEPENDENCIES
- edc-dataplane/edc-dataplane-base/build.gradle.kts
- edc-extensions/migrations/control-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/dataplaneinstance/V0_0_1__Init_Dataplaneinstance.sql
- edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/harness/StatusList2021.java
- gradle/libs.versions.toml
upgradeability tests
upgradeability tests are failing on `main
To fix that we have to change the `V0_0_1__Init_Dataplaneinstance.sql` to be equal to the one in 0.7.4. By doing so the migration from `0.8.0-rc2` to the next RC version `0.8.0-rc3` will fail instead.
Closes #1528
> fix: upgradeability tests

- edc-controlplane/edc-controlplane-base/build.gradle.kts
- edc-extensions/transfer-dataplane-signaling/build.gradle.kts
- edc-extensions/transfer-dataplane-signaling/src/main/java/org/eclipse/tractusx/edc/dataplane/transfer/signaling/DataPlaneSignalingFlowController.java
- edc-extensions/transfer-dataplane-signaling/src/main/java/org/eclipse/tractusx/edc/dataplane/transfer/signaling/TransferDataPlaneSignalingExtension.java
- edc-extensions/transfer-dataplane-signaling/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
- edc-extensions/transfer-dataplane-signaling/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/signaling/TransferDataPlaneSignalingExtensionTest.java
- edc-extensions/transfer-dataplane-signaling/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/signaling/flow/DataPlaneSignalingFlowControllerTest.java
- gradle/libs.versions.toml
- settings.gradle.kts
Add a fix related with the null dataplaneId value in a TransferProcess.
To avoid terminated null dp_id's errors. Similar to https://github.com/eclipse-edc/Connector/pull/4420
Please check https://github.com/eclipse-edc/Connector/issues/4418 for more context
Closes https://github.com/eclipse-tractusx/tractusx-edc/issues/1535
> Fix: dataplaneId null for older TransferProcesses

- .github/workflows/verify.yaml
- DEPENDENCIES
- edc-controlplane/edc-controlplane-base/build.gradle.kts
- edc-extensions/backport/README.md
- edc-extensions/backport/azblob-provisioner/README.md
- edc-extensions/backport/azblob-provisioner/build.gradle.kts
- edc-extensions/backport/azblob-provisioner/src/main/java/org/eclipse/edc/connector/provision/azure/AzureProvisionExtension.java
- edc-extensions/backport/azblob-provisioner/src/main/java/org/eclipse/edc/connector/provision/azure/blob/ObjectContainerProvisionedResource.java
- edc-extensions/backport/azblob-provisioner/src/main/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageConsumerResourceDefinitionGenerator.java
- edc-extensions/backport/azblob-provisioner/src/main/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageProvisioner.java
- edc-extensions/backport/azblob-provisioner/src/main/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageResourceDefinition.java
- edc-extensions/backport/azblob-provisioner/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
- edc-extensions/backport/azblob-provisioner/src/test/java/org/eclipse/edc/connector/provision/azure/blob/ObjectContainerProvisionedResourceTest.java
- edc-extensions/backport/azblob-provisioner/src/test/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageConsumerResourceDefinitionGeneratorTest.java
- edc-extensions/backport/azblob-provisioner/src/test/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageProvisionerTest.java
- edc-extensions/backport/azblob-provisioner/src/test/java/org/eclipse/edc/connector/provision/azure/blob/ObjectStorageResourceDefinitionTest.java
- edc-extensions/backport/azblob-provisioner/src/test/resources/hello.txt
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzureToAzureTest.java
- edc-tests/edc-end2end/end2end-transfer-cloud/build.gradle.kts
- edc-tests/edc-end2end/end2end-transfer-cloud/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AzureBlobHelper.java
- edc-tests/edc-end2end/end2end-transfer-cloud/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AzureToAzureEndToEndTest.java
- edc-tests/edc-end2end/end2end-transfer-cloud/src/test/java/org/eclipse/tractusx/edc/tests/transfer/MinioContainer.java
- edc-tests/edc-end2end/end2end-transfer-cloud/src/test/java/org/eclipse/tractusx/edc/tests/transfer/S3ToS3EndToEndTest.java
- edc-tests/edc-end2end/end2end-transfer-cloud/src/test/resources/hello.txt
- gradle/libs.versions.toml
- settings.gradle.kts
Backports the Azure Blob Provisioner extension into the `0.7.5` branch. The backport was done in the `main` line in PR #1536
being able to provision temporary SAS tokens for provider-push scenarios
> fix: backport AZ Blob Provisioner

- .github/workflows/publish-new-snapshot.yaml
- .github/workflows/run-all-tests.yml
This PR proposes a refactor to the `determine-version` job of the `publish-new-snapshot` workflow, that improves the job to resolve the correct snapshot version string from the gradle.properties every time. This version string is then used as input for the various publishing workflows.
As the publish-new-snapshot workflow can be manually activated, this improvement also allows for the creation of a snapshot from any branch.
To allow snapshots from bugfix branches.
In light of #1543, also took the opportunity to remove some unnecessary "listeners" from the run-all-tests workflow, making the file simpler.
- Removed any reference to the releases branch as its not needed anymore.
- Removed any reference to previews/* branches as they are not needed anymore.
- Checking if the …
> feat(snapshot workflow): Allow snapshots from bugfix branches

- gradle/libs.versions.toml
Cleanup version catalog from unused dependencies
make dependabot work again for `edc` dependencies
Closes #1559
> build: cleanup version catalog to make dependabot work again

- DEPENDENCIES
- edc-dataplane/edc-dataplane-base/build.gradle.kts
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/ParticipantRuntime.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/ParticipantRuntimeExtension.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/PgRuntimeExtension.java
- edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/Runtimes.java
- edc-tests/edc-controlplane/transfer-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/TransferWithTokenRefreshTest.java
- edc-tests/edc-dataplane/cloud-transfer-tests/build.gradle.kts
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzureToAzureTest.java
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/MultiCloudTest.java
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/S3ToS3Test.java
- edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/TestConstants.java
- edc-tests/runtime/iatp/runtime-memory-sts/build.gradle.kts
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/services/PolicyDefinitionServiceStub.java
- edc-tests/runtime/runtime-memory/build.gradle.kts
- edc-tests/runtime/runtime-postgresql/build.gradle.kts
- gradle/libs.versions.toml
Bump EDC to the latest snapshot
> build(deps): bump edc to 0.10.0-20240918-SNAPSHOT

- .github/actions/run-deployment-test/action.yml
- .github/actions/setup-helm/action.yml
- .github/actions/setup-kubectl/action.yml
- .github/workflows/deployment-test.yaml
- .github/workflows/helm-lint.yaml
- .github/workflows/release.yml
- .github/workflows/upgradeability-test.yaml
Set the 3 latest k8s versions in deployment-test.
TRG 5.10
- extracted composite actions for setup-helm and setup-kubectl, to keep the versions in a single file
Closes #1563
> ci: bump k8s versions in deployment test

- .github/workflows/secrets-scan.yml
- DEPENDENCIES
Adapt the TruffleHog workflow to use a dedicated commit version
As mentioned in https://github.com/eclipse-tractusx/sig-security/issues/86, the commit hash is the version the Eclipse Tractus-X project has agreed upon.
Closes #1581
> chore: Switch to Tractus-X recommended TruffleHog version

- edc-extensions/dcp/tx-dcp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/IatpIdentityExtension.java
- edc-extensions/dcp/tx-dcp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/identity/IatpIdentityExtractor.java
- edc-extensions/dcp/tx-dcp/src/test/java/org/eclipse/tractusx/edc/iam/iatp/IatpIdentityExtensionTest.java
- edc-extensions/dcp/tx-dcp/src/test/java/org/eclipse/tractusx/edc/iam/iatp/identity/IatpIdentityExtractorTest.java
- edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/IdentityExtractorTest.java
This PR prevents the upstream `DefaultDcpParticipantAgentServiceExtension` from being registered with the `ParticipantAgentService` by declaring a provider method for the `IatpIdentityExtractor`
the `IatpIdentityExtractor` was not added to the service context, which means, that at runtime, both the `DefaultDcpParticipantAgentServiceExtension` and the `IatpIdentityExtractor` are present.
That means, that whichever is registered first, determines the ID property of the ParticipantAgent, either `credentialSubject.Id`, or `credentialSubject.holderIdentifier`. We need the latter, because that contains the BPN.
The fact that this bug hasn't surfaced earlier is _pure chance_, because apparently the `IatpIdentityExtractor` got registered later.
> fix: prevent default identity extractor from being registered

- DEPENDENCIES
- charts/tractusx-connector-azure-vault/README.md
- charts/tractusx-connector-memory/README.md
- charts/tractusx-connector/README.md
- edc-extensions/iatp/tx-iatp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/IatpIdentityExtension.java
- edc-extensions/iatp/tx-iatp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/identity/IatpIdentityExtractor.java
- edc-extensions/iatp/tx-iatp/src/test/java/org/eclipse/tractusx/edc/iam/iatp/IatpIdentityExtensionTest.java
- edc-extensions/iatp/tx-iatp/src/test/java/org/eclipse/tractusx/edc/iam/iatp/identity/IatpIdentityExtractorTest.java
- edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/IdentityExtractorTest.java
Backports #34eced3e3e6a423ae367a5775ddd2469eb6c8da3
to appease the gods of software
> Backport: fix: prevent default DCP identity extractor from being registered

- .github/actions/publish-tag-and-release/action.yml
- .github/actions/setup-helm/action.yml
- .github/workflows/manual-release-bugfix.yml
- .github/workflows/release.yml
- .github/workflows/trigger-docker-publish.yaml
- .github/workflows/trigger-maven-publish.yaml
Backport .github folder from main branch
to get the updated workflows
> build: backport release workflow

- .github/workflows/publish-openapi-ui.yml
Add missing `GITHUB_TOKEN` attribute, that became mandatory after a [breaking change release](https://github.com/Legion2/swagger-ui-action/pull/464) of `Legion2/swagger-ui-action`
> build: fix publish openapi ui

- docs/migration/Version_0.7.x_0.8.x.md
Adds two sections to the 0.7.X -> 0.8.0 migration guide:
- About the possibility to use program args with the docker images
- About the agreement retirement featured
Improving the migration guide
> docs: added program args and agreement retirement section to 0.8.0 migration guide

- samples/edc-dast/edc-dast-extensions/src/main/java/org/eclipse/tractusx/edc/dast/DastSeedExtension.java
- samples/edc-dast/edc-dast-runtime/configuration.properties
Fixes dast scan on CI
https://github.com/eclipse-tractusx/tractusx-edc/actions/runs/12076803324/job/33678710703
> chore: fix dast scan

- edc-extensions/bpn-validation/README.md
Removed the deprecation warning from the BPN Policy
Updated the BPN Policy deprecation warning to turn it into a usage warning. 
The BPN Policy was marked for deprecation but it was decided to keep it - the docs didn't reflect that yet.
> docs(bpn-policy): Removed Deprecation Warning from BPN Policy 

- DEPENDENCIES
- docs/migration/Version_0.7.x_0.8.x.md
- edc-extensions/migrations/control-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/policy/V0_0_6__Avoid_null_profiles.sql
Add migration to fix the problem of null `profiles` column.
Avoid NPE
- there's a workaround for this error that can be applied before an 0.8.1 is released. Added a description in the migration guide.
> fix: add default empty array value for null policy profiles

- docs/usage/management-api-walkthrough/03_contractdefinitions.md
Added description on how to use private properties as asset selectors 
The docs are currently incomplete and the behaviour has changed between 0.5 and 0.7.
Not using the "privateProperties." prefix will still show the asset in the catalogue but then it's not negotiatable. A separate defect will be opened on that.
> docs(ContractDefinitions): Added description how to use private Properties in asset selectors

- DEPENDENCIES
- docs/usage/management-api-walkthrough/01_assets.md
This PR documents a feature that allows a Data Provider to add constant headers attached by the Provider Data Plane request to the backend.
This feature has been available for a long time and may be useful for non-productive scenarios where a backend API key is attached to the backend request.
https://github.com/eclipse-edc/Connector/blob/243ebc9b64fb1ccc08d3a78ebe669c5569175548/spi/data-plane/data-plane-http-spi/src/main/java/org/eclipse/edc/connector/dataplane/http/spi/HttpDataAddress.java#L216
> docs(mgmt): add static header config

- edc-extensions/bpn-validation/bpn-validation-api/src/main/java/org/eclipse/tractusx/edc/api/bpn/v3/BusinessPartnerGroupApiV3.java
Correct the documentation for creating a Policy with a constraint to match if the groups a BPNL is assigned are allowed to fetch the respective catalog.
Current documentation is not correct
Closes #1720
> docs: Correct BPNL Group Validation documentation for a valid Policy with a Collection

- README.md
Add a note to the readme to indicate, that Hashicorp Vault 1.18.1 is incompatible with the EDC
Discussed in the last weekly, see comment in #1772 
Closes #1772
> chore: Add known issues section to readme file

- DEPENDENCIES
- docs/migration/Version_0.8.x_0.9.x.md
Adds a guide to aid migration from tractusx-edc 0.8.X to 0.9.X.
Closes #1784
> docs: Added 0.8.X -> 0.9.X migration guide

- DEPENDENCIES
- build.gradle.kts
Forces versions:
To fix https://github.com/eclipse-tractusx/tractusx-edc/security/code-scanning/3157
- `com.azure:azure-core-http-netty` to `1.15.10`
- `software.amazon.awssdk:netty-nio-client` to `2.30.17`
To fix https://github.com/eclipse-tractusx/tractusx-edc/security/code-scanning/3066
- `net.minidev:json-smart` to `2.5.2`
#1791
> build(deps): force transitive dependencies to fix security checks

- .github/CODEOWNERS
- DEPENDENCIES
Add a codeowners file to ensure the committers being added as reviewers
To prevent wrong proposals for reviewers and to control who gets notified on changes
> chore: add codeowners file to define standard reviewer

- CHANGELOG.md
In Changelog, added pointer to the current releases on https://github.com/eclipse-tractusx/tractusx-edc/releases and clarified historic nature of the changelog file.
> (docs): Changelog - point to releases

- DEPENDENCIES
- edc-extensions/agreements/retirement-evaluation-core/build.gradle.kts
- edc-extensions/bpn-validation/bpn-validation-core/build.gradle.kts
- edc-tests/e2e-fixtures/build.gradle.kts
- edc-tests/runtime/mock-connector/build.gradle.kts
- gradle/libs.versions.toml
- spi/edr-spi/build.gradle.kts
Cleans up `junit` and `assertj` dependencies, that are provided by the `edc-build` gradle plugin.
Reduce dependencies maintenance
Part of #1848
> refactor: cleanup test dependencies

- DEPENDENCIES
- edc-dataplane/edc-dataplane-base/build.gradle.kts
- edc-extensions/dataplane/dataplane-proxy/dataplane-public-api-v2/build.gradle.kts
- edc-extensions/dataplane/dataplane-proxy/dataplane-public-api-v2/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/api/DataPlanePublicApiV2Extension.java
- edc-extensions/dataplane/dataplane-proxy/dataplane-public-api-v2/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/api/controller/ContainerRequestContextApi.java
- edc-extensions/dataplane/dataplane-proxy/dataplane-public-api-v2/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/api/controller/ContainerRequestContextApiImpl.java
- edc-extensions/dataplane/dataplane-proxy/dataplane-public-api-v2/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/api/controller/DataFlowRequestSupplier.java
- edc-extensions/dataplane/dataplane-proxy/dataplane-public-api-v2/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/api/controller/DataPlanePublicApiV2.java
- edc-extensions/dataplane/dataplane-proxy/dataplane-public-api-v2/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/api/controller/DataPlanePublicApiV2Controller.java
- edc-extensions/dataplane/dataplane-proxy/dataplane-public-api-v2/src/main/resources/META-INF/services/org.eclipse.edc.spi.system.ServiceExtension
- edc-extensions/dataplane/dataplane-proxy/dataplane-public-api-v2/src/main/resources/public-api-version.json
- edc-extensions/dataplane/dataplane-proxy/dataplane-public-api-v2/src/test/java/org/eclipse/tractusx/edc/dataplane/proxy/api/controller/DataFlowStartMessageSupplierTest.java
- edc-extensions/dataplane/dataplane-proxy/dataplane-public-api-v2/src/test/java/org/eclipse/tractusx/edc/dataplane/proxy/api/controller/DataPlanePublicApiV2ControllerTest.java
- gradle/libs.versions.toml
- settings.gradle.kts
Adds `dataplane-public-api-v2` in `dataplane` extensions.
As the `data-plane-public-api-v2` will be deprecated in the upstream, this PR adds an extension for this proxy implementation.
Closes #1780
> Add dataplane proxy public api extension module

- .github/workflows/generate-and-publish-dependencies.yaml
Publishes the new DEPEDENCIES file to the GitHub pages.
To keep deps information up to date, once the DEPENDENCIES file is updated the new version should be published in GH pages.
The change regarding PR to main triggering workflow is done now since it avoids publishing on new PR's and since is a change to be done related with the issue, was made here.
A following PR to update the NOTICE file will be proposed, was not included here to keep the focus on GH pages.
Relates to https://github.com/eclipse-tractusx/tractusx-edc/issues/1743
> feat: publish dependencies to GitHub pages

- .github/workflows/draft-release.yaml
Updates the NOTICE file with most recent DEPENDENCIES check outcome in release.
To have all the documentation up-to-date for each new release.
Closes https://github.com/eclipse-tractusx/tractusx-edc/issues/1743
> feat: Update NOTICE file with new DEPENDENCIES file

- build.gradle.kts
- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/build.gradle.kts
- edc-controlplane/edc-runtime-memory/build.gradle.kts
- edc-dataplane/edc-dataplane-hashicorp-vault/build.gradle.kts
- edc-tests/runtime/mock-connector/build.gradle.kts
- gradle/libs.versions.toml
- samples/edc-dast/edc-dast-runtime/build.gradle.kts
- samples/multi-tenancy/build.gradle.kts
This PR updates the Shadow plugin ID from the old `com.github.johnrengelman.shadow` to the actual `com.gradleup.shadow`, and moves the plugin declaration into the version catalog file.
To use the actual Shadow plugin ID and unify its declaration across the entire project.
Closes #1882
> feat: change shadow plugin id and move into version catalog

- edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java
- edc-tests/e2e/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractIatpConsumerPullTest.java
- edc-tests/e2e/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/CredentialSpoofTest.java
I just discovered that the IATP tests didn't test the interaction with the catalog correctly, they were hitting the federated catalog instead of the /catalog endpoint on management api, that was responding 404 (`not(200)` was ok).
Now they make more sense
> refactor(test): improve IATP tests assertions

- .github/workflows/verify.yaml
This PR updates the `verify` workflow to ensure the `generate-allure-report` job runs when the `Run-All-Tests` workflow is manually triggered by a tag.
To enable manual regeneration of the Allure report against a specific tag.
Closes #1928
> fix: execute the `generate-allure-report` job when the `Run-All-Tests` workflow is manually triggered by a tag.

- docs/development/decision-records/2025-04-17-expose-all-bpn-groups/README.md
Adds a Decision Record to expose all the BPN groups in a new endpoint.
Right now to get all BPN groups stored the user needs to retrieve all BPNs and their related groups and iterate over them. This can be time consuming and adding a new endpoint that returns all the BPN groups would simplify API usage.
Relates to #1898
> docs: Create DR to retrieve all BPN Groups

- edc-extensions/agreements/retirement-evaluation-api/src/main/java/org/eclipse/tractusx/edc/agreements/retirement/api/v3/AgreementsRetirementApiV3Controller.java
- edc-extensions/agreements/retirement-evaluation-api/src/test/java/org/eclipse/tractusx/edc/agreements/retirement/api/v3/AgreementsRetirementApiV3ControllerTest.java
- edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java
Stabilizes the agreements retirements api to v3 (was v3.1alpha before.)
Gained maturity.
This PR also moves the API the `/contractagreements/retirements` url path, as it makes sense for such actions to be under that domain.
Closes #1851
> feat: stabilize agreements retirement api to v3

- edc-extensions/bpn-validation/bpn-validation-api/src/main/java/org/eclipse/tractusx/edc/api/bpn/v3/BusinessPartnerGroupApiV3.java
- edc-extensions/bpn-validation/bpn-validation-api/src/main/java/org/eclipse/tractusx/edc/api/bpn/v3/BusinessPartnerGroupApiV3Controller.java
- edc-extensions/bpn-validation/bpn-validation-api/src/test/java/org/eclipse/tractusx/edc/api/bpn/v3/BusinessPartnerGroupApiV3ControllerTest.java
- edc-extensions/bpn-validation/bpn-validation-core/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/defaults/InMemoryBusinessPartnerStore.java
- edc-extensions/bpn-validation/bpn-validation-core/src/testFixtures/java/org/eclipse/tractusx/edc/validation/businesspartner/store/BusinessPartnerStoreTestBase.java
- edc-extensions/bpn-validation/bpn-validation-spi/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/spi/BusinessPartnerStore.java
- edc-extensions/bpn-validation/business-partner-store-sql/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/store/sql/BusinessPartnerGroupStatements.java
- edc-extensions/bpn-validation/business-partner-store-sql/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/store/sql/PostgresBusinessPartnerGroupStatements.java
- edc-extensions/bpn-validation/business-partner-store-sql/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/store/sql/SqlBusinessPartnerStore.java
Adds a new `/groups` endpoint to resolve all BPN Groups. Implementation of [this Decision Record](https://github.com/eclipse-tractusx/tractusx-edc/pull/1908).
To ease the listing of all BPN groups stored.
As defined in the DR, this endpoint is added in the `BusinessPartnerGroupApiV3`.
Request:
GET /v3/business-partner-groups/groups
Example response:
```
{
"tx:groups": [
"group2",
"group4",
"group13",
"group10",
"group3",
"group1",
"group5"
],
"@context": {...}
}
```
Closes #1898
> Add implementation for exposing all BPN groups.

- .github/workflows/verify.yaml
This PR modifies the `Verif`y workflow to correctly resolve the path to the allure-results directory.
To enable the generation of the Allure report for end-to-end tests.
Closes #1947
> fix: update the path to the correct allure-results directory

- .github/workflows/verify.yaml
This PR avoid using gradle cache when executing end-to-end tests in the `Verify` workflow
To ensure that end-to-end tests always run and allow the generation of an accurate Allure report.
Part of #1952
> fix: avoid using gradle cache for end-to-end tests execution

- edc-controlplane/edc-controlplane-base/build.gradle.kts
- edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java
- edc-tests/runtime/iatp/runtime-memory-iatp-dim-ih/build.gradle.kts
- edc-tests/runtime/iatp/runtime-memory-iatp-ih/build.gradle.kts
- edc-tests/runtime/iatp/runtime-memory-sts/build.gradle.kts
- edc-tests/runtime/runtime-postgresql/build.gradle.kts
- gradle/libs.versions.toml
- samples/edc-dast/edc-dast-runtime/build.gradle.kts
- samples/multi-tenancy/build.gradle.kts
Exclude `org.eclipse.edc:identity-trust-sts-remote-client` from the controlplane-base module.
Fix bug
Using upstream BOM files ([PR](https://github.com/eclipse-tractusx/tractusx-edc/pull/1937)) we also inherited that module, that as shown in logs we received from users, it was overriding 2 services:
```
WARNING 2025-05-13T01:58:53.310725006 A service of the type org.eclipse.edc.iam.identitytrust.sts.remote.StsRemoteClientConfiguration was already registered and has now been replaced with a StsRemoteClientConfiguration instance.
WARNING 2025-05-13T01:58:53.316061488 A service of the type org.eclipse.edc.iam.identitytrust.spi.SecureTokenService was already registered and has now been replaced with a RemoteSecureTokenService instance.
```
Unfortunately in some e2e runtimes we were actually …
> fix: exclude sts client extension from controlplane-base

- .github/workflows/release.yml
At the moment it's not possible to release from `release/` branches (sounds like an oxymoron :D )
> build: permit release from release/* branches

- edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/build.gradle.kts
Explicitly exclude the `target-node-directory-sql` extension
To have our file based target-node working correctly.
- if no file system target-node directory is provided, federated catalog will be disabled, so we can consider this as the default behavior
Closes #1965
> fix: exclude sql target node extension

- LICENSE
- charts/tractusx-connector-memory/LICENSE
- charts/tractusx-connector/LICENSE
- Removed Catena-X Copyright and substituted with empty copyright owner
As specified in this issue #2029 the Licenses used are pointing to Catena-X and that is not true anymore since the consortia died. Or you add the Catena-X Automotive Network e.V.  Association or you remove it so it valid for all the eclipse contributors.
I am not sure if it should be the eclipse foundation.
I am removing it so it would be valid for everyone like in other repos.
Closes #2029
> fix: restored copyright to all eclipse contributors

- .github/workflows/publish-new-snapshot.yaml
- .github/workflows/trigger-maven-publish.yaml
Change the credential usage so that publishing to maven central works. 
The switch from the sonatype oss repo to central broke the build.
Closes # #2021
> fix: publish snapshots to maven central

- edc-extensions/event-subscriber/src/README.md
Added README.md file to the `Event subscriber extension`
In order to document basic configuration and purpose of aforementioned extension
N/A
Closes #2093
> docs: add README to OTEL event subscriber extension

- docs/development/decision-records/2025-07-09-logging_and_metrics_framework/README.md
- docs/development/decision-records/2025-07-09-logging_and_metrics_strategy/README.md
A decision record that describes the overall decision concerning how logging information and further events are handled by the connector and the approach to compute metrics for better operations of a connector.
The framework described allows a more standardized and streamlined operation of connectors. Major information is made available in a way, that is easily processable and which allows to get an overview over current activities within a connector on a technical level as well as on a domain level.
Fixes #1745
> doc: add decision record for logging and metrics framework

- docs/development/decision-records/2025-07-16-adoption-of-log4j/README.md
Adds a decision record about the adoption of log4j as the standard logging framework for tractusx-edc.
Rational for this PR is well explained in the DR.
Part of #1852 
Aligned with https://github.com/eclipse-tractusx/tractusx-edc/pull/2085
Aligned with https://github.com/eclipse-tractusx/sig-release/issues/1280
> docs: DR for log4j2 as logging framework

- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/MatchType.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/MockServiceExtension.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/RecordedRequest.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/RecordedResponseDeserializer.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/ResponseQueue.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/ServiceFailureDeserializer.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/api/instrumentation/InstrumentationApi.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/api/instrumentation/InstrumentationApiController.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/services/AbstractServiceStub.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/services/AssetServiceStub.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/services/ContractAgreementServiceStub.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/services/ContractDefinitionServiceStub.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/services/ContractNegotiationServiceStub.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/services/PolicyDefinitionServiceStub.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/services/TransferProcessServiceStub.java
- edc-tests/runtime/mock-connector/src/main/java/org/eclipse/tractusx/edc/mock/services/VersionServiceStub.java
Deprecates the mock connector runtime since the v0.11.0.
This runtime does not seem to be used by anyone and so the effort of maintaining it is unnecessary.
Added javadoc due checkstyle's failing.
Closes #1918
> Deprecate the Mock Connector Runtime

- .github/workflows/publish-new-snapshot.yaml
This PR makes it possible to run the "Publish new snapshot" workflow manually with identification of whether it is dated or not.
To provide flexibility in producing daily SNAPSHOT builds outside of the weekly schedule.
As we do not use the `bugfix/*` in the new [release process](https://github.com/eclipse-tractusx/tractusx-edc/tree/main/docs/development/decision-records/2025-05-26-release-process), it will be changed to `release/*`
Closes #2130
> feat: Allow to create dated SNAPSHOT manually

- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementCredentialConstraintFunction.java
- edc-tests/e2e/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractIatpConsumerPullTest.java
- edc-tests/e2e/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/harness/DataspaceIssuer.java
- edc-tests/e2e/policy-tests/src/test/java/org/eclipse/tractusx/edc/tests/policy/PolicyDefinitionEndToEndTest.java
* add validation for the new data constraints which were introduced in the [cx-odrl-profile](https://github.com/catenax-eV/cx-odrl-profile/tree/main/schema/constraint)
* add validation for the framework constraint
To ensure that policies are valid
* tests are added to validate that the changes work correctly
Refs: #2083
> feat(constraint): add validation for framework constraint

- build.gradle.kts
Forces netty-codec-http2 to version 4.1.124.Final.
To fix the attached finding.
Also removed the forcing of netty-nio-client to 2.31.77 since this transitive dependency was updated upstream.
Closes https://github.com/eclipse-tractusx/tractusx-edc/security/code-scanning/5186
> fix: force netty-codec-http2 to version 4.1.124.Final

- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/validator/UsagePolicyValidator.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/CxPolicyDefinitionValidatorTest.java
- edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/validator/UsagePolicyValidatorTest.java
- edc-extensions/cx-policy/src/testFixtures/java/org/eclipse/tractusx/edc/policy/cx/validator/PolicyBuilderFixtures.java
- edc-extensions/dcp/tx-dcp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/scope/CredentialScopeExtractor.java
- edc-extensions/dcp/tx-dcp/src/test/java/org/eclipse/tractusx/edc/iam/iatp/scope/CredentialScopeExtractorTest.java
- edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/MockVcIdentityService.java
- edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/helpers/PolicyHelperFunctions.java
- edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/runtimes/Runtimes.java
- edc-tests/e2e/policy-tests/src/test/java/org/eclipse/tractusx/edc/tests/policy/PolicyDefinitionEndToEndTest.java
- edc-tests/e2e/policy-tests/src/test/java/org/eclipse/tractusx/edc/tests/policy/PolicyMonitorEndToEndTest.java
- edc-tests/e2e/transfer-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/TransferPullEndToEndTest.java
Adds a new json validator for usage policy validation. This validator checks whether a `FrameworkAgreement` and a `UsagePurpose` constraint are present in a given usage policy. Fails the validation if any of these constraints is missing.
Policy standard compliance
Updates the `CredentialScopeExtractor` to check whether a scope contains a valid credential type before returning it, so that it does not extract e.g. a scope for a non-existing type like `UsagePurposeCredential`, as that leads to a failure during credential request.
Also updates the mock identity service to always return a `DataExchangeGovernanceCredential`, as the corresponding policy constraint now is included in every usage policy.
> feat: validate required usage policy constraints

- .github/workflows/trigger-maven-publish.yaml
- gradle/libs.versions.toml
Switch the maven artifacts publication to the "new way", so, instead to publish them to the staging repo ([deprecated method](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/)), they gets published directly using APIs (preferred method) by using the [`gradle-maven-publish-plugin`](https://github.com/vanniktech/gradle-maven-publish-plugin)
Release publication will work as well. (tested upstream)
- I called the upstream `publish-maven-artifacts` action because the way we publish is strictly dependent to the edc-build plugin, so there's no reason to maintan that piece of code also in tractusx-edc
Closes #2178
> build: adapt maven publication to the new flow

- edc-extensions/migrations/control-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/contractnegotiation/V0_0_10__Alter_ContractNegotiation_CreateLeaseIndex.sql
- edc-extensions/migrations/control-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/policy-monitor/V0_0_3__Alter_PolicyMonitor_CreateLeaseIndex.sql
- edc-extensions/migrations/control-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/transferprocess/V0_0_17__Alter_TransferProcess_CreateLeaseIndex.sql
- edc-extensions/migrations/data-plane-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/dataplane/V0_0_6__Alter_Dataplane_CreateLeaseIndex.sql
- edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/TestRuntimeConfiguration.java
This PR adds flyway migrations for new indexes which are not created by Postgres automatically for foreign keys. The same indexes have been added to upstream's schema.sql files (https://github.com/eclipse-edc/Connector/issues/5179). This will accelerate the deletion of leases and selects of contract negotiations.
Closes #2181
> perf: add index for foreign key references

- .github/workflows/draft-release.yaml
Allow the RCs to be created with restricted dependencies.
A release candidate might be released with restricted dependencies to give time for other teams to start testing with the candidate meanwhile the IP reviews are conducted. However, official releases should not be allowed restricted dependencies.
>  feat: allow release of rcs with restricted dependencies 

- edc-controlplane/edc-controlplane-base/build.gradle.kts
- edc-dataplane/edc-dataplane-base/build.gradle.kts
- edc-extensions/log4j2-monitor/build.gradle.kts
- gradle/libs.versions.toml
Added log4j2 opentelemetry appender dependency 
In order to integrate OTEL with log4j2 and umbrella helm charts
Blocking:
[[TAP 7.2] - feat(observability): Log4j2 integration with OTEL](https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/316)
> feat - added otel appender for log4j2 [TAP 7.2]

- .github/release.yaml
fixes automatic PR labeling for breaking changes on release notes
Breaking changes were not being correctly identified.
closes #2193
> fix: automatic PR labeling for breaking changes on release notes

- charts/tractusx-connector/README.md
- charts/tractusx-connector/values.yaml
- edc-tests/deployment/src/main/resources/helm/tractusx-connector-test.yaml
Changes the used bitnami images to the legacy repository.
Due to https://github.com/bitnami/containers/issues/83267
Closes #2200 
To be considered for #2210
> chore: change bitnami images to bitnamilegacy

- charts/tractusx-connector-memory/templates/deployment-runtime.yaml
- charts/tractusx-connector/templates/deployment-controlplane.yaml
Remove the EDC_DCP_V08_FORCED environment setting from the chart templates
In 0.10.0 this was needed to enforce the usage of the old DCP protocol, since version 0.11.0 uses the new protocol, this setting must not be set.
Related to: #2212
> fix: Remove switch to use dcp 1.0 from charts

- core/json-ld-core/src/main/resources/document/tx-v1.jsonld
Revert deletion of context file, as this is published on github pages. In order to prevent backward compatibility issues, the file is added, but not loaded in the connector.
Because the resons for the publication is unknown and it might be needed by previous versions of the connector
> fix: Revert file deletion to still publish on github pages

- edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/businesspartner/BusinessPartnerGroupConstraintFunction.java
- edc-tests/e2e-fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/helpers/PolicyHelperFunctions.java
- edc-tests/e2e/catalog-tests/src/test/java/org/eclipse/tractusx/edc/tests/catalog/CatalogTest.java
Updates the evaluation in `BusinessPartnerGroupConstraintFunction` to consider that the right operand may have been created as either a string or an array. If the right operand is created as a string, the set of allowed groups contains the group names as-is, but if the right operand is created as an array, the set of allowed groups contains the group names in the following format: `{@value={chars=<group-name>, string=<group-name>, valueType=STRING}}`.
Previously, the evaluation considered the right operand only as string, causing the evaluation to fail if the right operand was created as an array.
Relates to #2221
> fix: evaluate BPN group constraint with string or array

- docs/migration/2025-09-Version_0.10.x_0.11.x.md
- edc-extensions/connector-discovery/connector-discovery-api/src/main/java/org/eclipse/tractusx/edc/discovery/v4alpha/api/ConnectorDiscoveryV4AlphaApi.java
Removes an unnecessary trailing comma from an ConnectorDiscoveryV4AlphaAPI example.
It was messing with formatting in the Swagger UI for that particular example.
Closes #2262
> fix: ConnectorParamsDiscoveryResquest format
