charts/edc-controlplane/Chart.yaml, charts/edc-dataplane/Chart.yaml
set correct URL in `Chart.yaml` for identifier `home`.
=> chore: helm chart fix url (home)

CHANGELOG.md, charts/edc-controlplane/Chart.yaml, charts/edc-controlplane/README.md, charts/edc-dataplane/Chart.yaml, charts/edc-dataplane/README.md, edc-controlplane/edc-controlplane-base/pom.xml, edc-controlplane/edc-controlplane-memory/pom.xml, edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/pom.xml, edc-controlplane/edc-controlplane-postgresql/pom.xml, edc-controlplane/pom.xml, edc-dataplane/edc-dataplane-azure-vault/pom.xml, edc-dataplane/edc-dataplane-base/pom.xml, edc-dataplane/edc-dataplane-hashicorp-vault/pom.xml, edc-dataplane/pom.xml, edc-extensions/business-partner-validation/pom.xml, edc-extensions/cx-oauth2/pom.xml, edc-extensions/data-encryption/pom.xml, edc-extensions/dataplane-selector-configuration/pom.xml, edc-extensions/hashicorp-vault/pom.xml, edc-extensions/pom.xml, edc-extensions/postgresql-migration/pom.xml, edc-tests/pom.xml, pom.xml
Carry 0.1.6 release changes from product-edc.
Details:
https://github.com/catenax-ng/product-edc/releases/tag/0.1.6
=> Release 0.1.6

.github/workflows/helm-chart-release.yaml
=> chore: add workflow to release helm chart

charts/edc-controlplane/Chart.yaml, charts/edc-dataplane/Chart.yaml
=> chore: bump chart version to trigger Helm chart releaser

.github/workflows/build.yaml, .github/workflows/draft-new-release.yaml, .github/workflows/helm-chart-release.yaml, .github/workflows/publish-new-release.yml
This PR fixes some permission issues of our release workflows
make release workflows work again :)
=> Fix: workflow permission issues in preparation for the release pipeline

.github/workflows/build.yaml
In my previous PR (#144) I had a syntactic error which is now fixed.
=> fix: multiline comment

docs/development/Run-business-tests-local.md
Working on this PR #159 , i had a failing step on markdown linter.  
Probably in the merge phase something broke or the linter PR wasn't rebase correctly
This PR fixes one minor error
=> chore(md-linter): Fix markdown linter error

docs/development/decision-records/2023-04-11_refactor_helmcharts/README.md
adds a decision record about refactoring our helm charts as per meeting of March 20th 2023.
outlining the reasoning and especially the technical approach behind the decision
=> docs: decision record about refactoring helm charts

edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/Connector.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/ConnectorFactory.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/Constants.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/ControlPlaneAdapterSteps.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/DataManagementAPI.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/Environment.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/HttpProxyTransferSteps.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/NegotiationSteps.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/PolicyStepDefs.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/S3FileTransferStepsDefs.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/Asset.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/BusinessPartnerNumberConstraint.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/ContractDefinition.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/ContractNegotiation.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/ContractOffer.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/HttpProxySourceDataAddress.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/Negotiation.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/OrConstraint.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/PayMeConstraint.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/Permission.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/Policy.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/S3DataAddress.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/Transfer.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/data/TransferProcess.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/util/DatabaseCleaner.java, edc-tests/cucumber/src/test/java/org/eclipse/tractusx/edc/tests/util/S3Client.java
This PR is the first one of the story #150 lombok for the DR  #143 .
The main target of this pr is the `edc-tests` modules. In particular the `edc-tests:cucumber` one.
Closes #151
=> Remove lombok from edc tests

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/verify.yaml
adds a markdown file that is used as template for PR descriptions
consistent pr desc
=> chore: add template for pull-request descriptions

.github/dependabot.yml, .github/workflows/build.yaml, .github/workflows/business-tests.yaml, .github/workflows/draft-new-release.yaml, .github/workflows/helm-chart-release.yaml, .github/workflows/helm-lint.yaml, .github/workflows/kics.yml, .github/workflows/publish-new-release.yml, .github/workflows/trivy.yml, .github/workflows/verify.yaml, charts/tractusx-connector/templates/deployment-controlplane.yaml, charts/tractusx-connector/templates/deployment-dataplane.yaml, docs/development/decision-records/2023-02-09-release-process/README.md, docs/development/decision-records/2023-02-27_testing/README.md, edc-controlplane/edc-controlplane-memory-hashicorp-vault/notice.md, edc-controlplane/edc-controlplane-memory/notice.md, edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/notice.md, edc-controlplane/edc-controlplane-postgresql/notice.md, edc-dataplane/edc-dataplane-azure-vault/notice.md, edc-dataplane/edc-dataplane-hashicorp-vault/notice.md, pr_etiquette.md
updates branch names in our documentation and in our workflow files, most notably in the release pipelines.
git branch names have been updated
Closes #214 
Closes #216 
_replaces #217_
=> refactor: rename git branches

.github/workflows/business-tests.yaml, charts/tractusx-connector-memory/templates/deployment-runtime.yaml, charts/tractusx-connector-memory/values.yaml, charts/tractusx-connector/templates/deployment-controlplane.yaml, charts/tractusx-connector/values.yaml, edc-extensions/business-partner-validation/build.gradle.kts, edc-extensions/business-partner-validation/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/BusinessPartnerValidationExtension.java, edc-extensions/business-partner-validation/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/AbstractBusinessPartnerValidation.java, edc-extensions/business-partner-validation/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/BusinessPartnerDutyFunction.java, edc-extensions/business-partner-validation/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/BusinessPartnerPermissionFunction.java, edc-extensions/business-partner-validation/src/main/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/BusinessPartnerProhibitionFunction.java, edc-extensions/business-partner-validation/src/test/java/org/eclipse/tractusx/edc/validation/businesspartner/BusinessPartnerValidationExtensionTest.java, edc-extensions/business-partner-validation/src/test/java/org/eclipse/tractusx/edc/validation/businesspartner/functions/AbstractBusinessPartnerValidationTest.java, edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/MultiRuntimeTest.java, edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/lifecycle/Participant.java, edc-tests/e2e-tests/src/test/java/org/eclipse/tractusx/edc/tests/HttpConsumerPullWithProxyTest.java, settings.gradle.kts
Adds a log entry (configurable) when evaluating the policy on `ContractAgreement`
Closes #244
=> feat(BusinessPartnerValidation): adds logging if it's enabled on contract agreement validation

.github/workflows/veracode.yaml, CHANGELOG.md
Fixed a typo in Veracode action.
Veracode action fails
=> fix: Typo in veracode action

DEPENDENCIES
Update 3rd party DEPENDENCIES file
The DEPENDENCIES file was out of date
Closes #281
=> chore: Update 3rd party DEPENDENCIES file

charts/tractusx-connector/templates/deployment-controlplane.yaml
In the controlplane deployment a required value was misspelled.
_-_
_-_
<hr />
Marco Lecheler [marco.lecheler@mercedes-benz.com](mailto:marco.lecheler@mercedes-benz.com) Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md))
=> chore(helm): fix typo in required value in cp deployment

edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile, edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile, edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile, edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile, edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
updates curl (used in Dockerfiles) to `8.1.1-r1`
=> chore: update curl version to 8.1.1-r1

edc-extensions/control-plane-adapter-api/src/test/java/org/eclipse/tractusx/edc/api/cp/adapter/transform/JsonObjectToNegotiateEdrRequestDtoTransformerTest.java, edc-extensions/control-plane-adapter-callback/src/main/java/org/eclipse/tractusx/edc/cp/adapter/callback/InProcessCallbackMessageDispatcher.java, gradle.properties, gradle/libs.versions.toml
Upgrades to EDC 0.1.2, fixes compile errors
Stay abreast with latest EDC developments
=> chore: upgrade to EDC 0.1.2

docs/development/postman/collection.json
Following requests have been adapted:
- Create Policy
- Get all Policies
- Initiate Negotiation
The Policy implementation has been changed in upstream.
Closes #534
=> fix: Adapt Postman Collection for RC1/RC2

CHANGELOG.md
=> chore(build): fix `CHANGELOG.md` lint

charts/tractusx-connector-azure-vault/templates/NOTES.txt, charts/tractusx-connector-legacy/templates/NOTES.txt, charts/tractusx-connector-memory/templates/NOTES.txt, charts/tractusx-connector/templates/NOTES.txt
Fix deployment notes
The deployments notes were showing wrong information
Closes #514
=> fix: Deployment notes

CHANGELOG.md, gradle.properties
=> chore(build): updates to EDC 0.1.3

DEPENDENCIES
Updates the DEPENDENCIES file, adding the latest approvals from IPlab review requests.
Keeping up-to-date. CI builds will fail until this change is merged.
- the following new requests have been filed and incorporated:
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9269
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9270
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9271
=> chore: update DEPENDENCIES, add approvals

edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/SsiMiwConfigurationExtension.java, edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/SsiMiwOauth2ClientExtension.java, edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/oauth2/MiwOauth2ClientImpl.java, edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/utils/PathUtils.java, edc-extensions/ssi/ssi-miw-credential-client/src/test/java/org/eclipse/tractusx/edc/iam/ssi/miw/SsiMiwConfigurationExtensionTest.java, edc-extensions/ssi/ssi-miw-credential-client/src/test/java/org/eclipse/tractusx/edc/iam/ssi/miw/SsiMiwOauth2ClientExtensionTest.java, edc-extensions/ssi/ssi-miw-credential-client/src/test/java/org/eclipse/tractusx/edc/iam/ssi/miw/utils/PathUtilsTest.java
Adds tolerance to eventual trailing slash in MIW or token URLs
User experience
Closes #580
=> feat(SSI): adds tolerance to eventual trailing slash in MIW or token URLs

docs/migration/Version_0.4.x_0.5.x.md
Updates the Migration Guide for `0.4.x -> 0.5.x`.
documentation
=> docs: update migration guide for 0.5.0

charts/tractusx-connector-azure-vault/README.md, charts/tractusx-connector-azure-vault/README.md.gotmpl, charts/tractusx-connector-memory/README.md, charts/tractusx-connector-memory/README.md.gotmpl, charts/tractusx-connector/README.md, charts/tractusx-connector/README.md.gotmpl
This PR simply adds a link to the MIW to the readmes.
If that is not desired to link to other repos or this is not the correct repo of the MIW, please just close this PR/comment.
CC @SeBuSov @stephanbcbauer
=> docs: add link to MIW to readme

charts/tractusx-connector-azure-vault/README.md, charts/tractusx-connector-azure-vault/values.yaml, charts/tractusx-connector-legacy/README.md, charts/tractusx-connector-legacy/values.yaml, charts/tractusx-connector-memory/README.md, charts/tractusx-connector-memory/values.yaml, charts/tractusx-connector/README.md, charts/tractusx-connector/values.yaml
- Remove unused values
- Add description to edc specific values
To improve helm charts
Closes #469
=> chore: Improve Helm Chart documentation

.github/workflows/verify.yaml
This PR uses the dependency check flow from upstream EDC.
re-use existing code, avoid duplication
=> feat(ci): use dependency check from upstream EDC

charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml
Fixing small typo in azure-vault Helm chart for required field `.Values.controlplane.endpoints.management.authKey`.
<hr />
Marco Lecheler [marco.lecheler@mercedes-benz.com](mailto:marco.lecheler@mercedes-benz.com) Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md))
=> chore(helm): fix typo for controlplane.endpoints.management.authKey

.github/release.yaml
Adds some config to the automatic GH releases. Release notes will now be grouped into:
- Bugfixes
- New Features & Improvements
- Documentation
dependabot PRs will be ignored in the release notes.
Better structured release notes.
=> feat(release): add config for GH releases

.github/workflows/veracode.yaml, .github/workflows/verify.yaml, build.gradle.kts, docs/kit/development-view/page03_project_structure.md
Removes spotless dep and run in actions
not used
=> chore: remove spotless dep 

charts/tractusx-connector-azure-vault/README.md, charts/tractusx-connector-azure-vault/README.md.gotmpl, charts/tractusx-connector-memory/README.md, charts/tractusx-connector-memory/README.md.gotmpl, charts/tractusx-connector/README.md, charts/tractusx-connector/README.md.gotmpl, docs/migration/Version_0.4.x_0.5.x.md
Updates the MIW link in our docs to [this](https://github.com/eclipse-tractusx/managed-identity-wallet)
consistency, docs
=> chore: updates MIW link

docs/development/decision-records/2023-08-03_improve_bpn_validation/README.md, docs/development/decision-records/2023-08-24-proprietrary-extensions/README.md
Documents the decision regarding the integration of Azure Blob Storage and future integrations.
Related to: #661
=> Decision record proprietary extensions

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/workflows/stale-bot.yml
Adds a better feature request template and a stalebot according to the [decision record](https://github.com/eclipse-tractusx/tractusx-edc/tree/main/docs/development/decision-records/2023-09-08_issue_quality_stalebot).
Issue quality
=> add stalebot

DEPENDENCIES
updates DEPENDENCIES file
clear all deps ready for new release
=> chore: updates DEPENDENCIES file

edc-controlplane/edc-controlplane-memory-hashicorp-vault/notice.md, edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile, edc-controlplane/edc-controlplane-postgresql-azure-vault/notice.md, edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile, edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/notice.md, edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile, edc-controlplane/edc-runtime-memory/notice.md, edc-controlplane/edc-runtime-memory/src/main/docker/Dockerfile, edc-dataplane/edc-dataplane-azure-vault/notice.md, edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile, edc-dataplane/edc-dataplane-hashicorp-vault/notice.md, edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile, edc-tests/miw-tests/src/test/resources/docker-environment/docker-compose.yaml
update temurin to 17.0.8.1_1-jre-alpine
=> chore: update temurin to 17.0.8.1_1-jre-alpine

charts/tractusx-connector-azure-vault/Chart.yaml, charts/tractusx-connector-azure-vault/README.md, charts/tractusx-connector-memory/Chart.yaml, charts/tractusx-connector-memory/README.md, charts/tractusx-connector/Chart.yaml, charts/tractusx-connector/README.md, gradle.properties
Bump version in gradle and charts to 0.5.3 for release
=> Release 0.5.3

charts/tractusx-connector-azure-vault/README.md, charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml, charts/tractusx-connector-azure-vault/values.yaml, charts/tractusx-connector-memory/README.md, charts/tractusx-connector-memory/templates/deployment-runtime.yaml, charts/tractusx-connector-memory/values.yaml, charts/tractusx-connector/README.md, charts/tractusx-connector/templates/deployment-controlplane.yaml, charts/tractusx-connector/values.yaml
Increase EDR token validity to 30 days
Lowering down the number of transfer process for data transfers
Closes #927
=> feat: increase EDR token validity

DEPENDENCIES, edc-controlplane/edc-controlplane-postgresql-azure-vault/notice.md, edc-controlplane/edc-controlplane-postgresql-azure-vault/src/main/docker/Dockerfile, edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/notice.md, edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/src/main/docker/Dockerfile, edc-controlplane/edc-runtime-memory/notice.md, edc-controlplane/edc-runtime-memory/src/main/docker/Dockerfile, edc-dataplane/edc-dataplane-azure-vault/notice.md, edc-dataplane/edc-dataplane-azure-vault/src/main/docker/Dockerfile, edc-dataplane/edc-dataplane-hashicorp-vault/notice.md, edc-dataplane/edc-dataplane-hashicorp-vault/src/main/docker/Dockerfile
_Briefly describe what your PR changes, which features it adds/modifies._
Closes #990
=> build(deps): upgrade eclipse-temurin to 17.0.9_9-jre-alpine

.github/workflows/verify.yaml, edc-extensions/edr/edr-callback/src/main/java/org/eclipse/tractusx/edc/callback/TransferProcessLocalCallback.java, edc-extensions/edr/edr-callback/src/test/java/org/eclipse/tractusx/edc/callback/TestFunctions.java, edc-extensions/edr/edr-callback/src/test/java/org/eclipse/tractusx/edc/callback/TransferProcessLocalCallbackTest.java, edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/api/MiwApiClientImpl.java, edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/api/MiwFallbackFactories.java, edc-extensions/ssi/ssi-miw-credential-client/src/test/java/org/eclipse/tractusx/edc/iam/ssi/miw/api/MiwApiClientImplTest.java
=> chore: backport of #837 in 0.5.x

.github/workflows/trivy.yml
=> chore: trivy fix

DEPENDENCIES, edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/ConsumerAssetRequestController.java, edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/test/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/model/ConsumerAssetRequestControllerTest.java, edc-extensions/dataplane-proxy/edc-dataplane-proxy-provider-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/provider/api/gateway/ProviderGatewayController.java, edc-extensions/transferprocess-sftp-client/src/main/java/org/eclipse/tractusx/edc/transferprocess/sftp/client/SftpDataSinkFactory.java, edc-extensions/transferprocess-sftp-client/src/main/java/org/eclipse/tractusx/edc/transferprocess/sftp/client/SftpDataSourceFactory.java, edc-extensions/transferprocess-sftp-client/src/test/java/org/eclipse/tractusx/edc/transferprocess/sftp/client/SftpDataSinkFactoryTest.java, edc-extensions/transferprocess-sftp-client/src/test/java/org/eclipse/tractusx/edc/transferprocess/sftp/client/SftpDataSourceFactoryTest.java, edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzureToAzureTest.java, edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/MultiCloudTest.java, edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/S3ToS3Test.java
fix compile error  after DataFlowRequest refactor
build fix
=> chore: fix compile error after DataFlowRequest refactor

DEPENDENCIES, edc-extensions/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/ConsumerAssetRequestController.java, edc-extensions/dataplane-proxy/edc-dataplane-proxy-provider-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/provider/api/gateway/ProviderGatewayController.java, edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/transferprocess/V0_0_14__Alter_TransferProcess_AddDataPlaneId.sql, edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/AzureToAzureTest.java, edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/MultiCloudTest.java, edc-tests/edc-dataplane/cloud-transfer-tests/src/test/java/org/eclipse/tractusx/edc/dataplane/transfer/test/S3ToS3Test.java
fixes compile issue after trackable removal
build fix
=> chore: fix compile issue after trackable removal

edc-extensions/bpn-validation/README.md
update docs for businesspartnergroup extension.
Closes #1116
=> docs(bpngroups): update supported operators

DEPENDENCIES, edc-extensions/edr/edr-api/src/test/java/org/eclipse/tractusx/edc/api/edr/EdrApiTest.java
fix compile error after upstream changes
fix build
=> chore: fix compile error after upstream transformers refactor

DEPENDENCIES, edc-controlplane/edc-controlplane-base/build.gradle.kts, edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/common/AbstractDynamicCredentialConstraintFunction.java, edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/dismantler/DismantlerCredentialConstraintFunction.java, edc-extensions/cx-policy/src/main/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementCredentialConstraintFunction.java, edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/CredentialFunctions.java, edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/dismantler/DismantlerConstraintFunctionTest.java, edc-extensions/cx-policy/src/test/java/org/eclipse/tractusx/edc/policy/cx/framework/FrameworkAgreementConstraintFunctionTest.java, edc-extensions/iatp/tx-iatp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/scope/CredentialScopeExtractor.java
- import missing `cx-policy` module in the control-plane-base distribution
- fix capitalize in the scope extractor
- support properties without namespace in policy functions
=> chore: fixes after more tests

DEPENDENCIES, edc-extensions/bpn-validation/business-partner-store-sql/src/test/java/org/eclipse/tractusx/edc/validation/businesspartner/store/sql/SqlBusinessPartnerStoreTest.java, edc-extensions/migrations/control-plane-migration/src/test/java/org/eclipse/tractusx/edc/postgresql/migration/AssetPostgresqlMigrationExtensionTest.java, edc-extensions/provision-additional-headers/src/test/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersProvisionedResourceTest.java, edc-extensions/provision-additional-headers/src/test/java/org/eclipse/tractusx/edc/provision/additionalheaders/AdditionalHeadersResourceDefinitionTest.java, edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/MockBpnIdentityService.java, edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/dispatchers/DimDispatcher.java, edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/dispatchers/KeycloakDispatcher.java
fix compile issue after type manager refactor upstream
=> chore: fix compile issue after type manager refactor upstream

DEPENDENCIES, charts/tractusx-connector-azure-vault/README.md, charts/tractusx-connector-azure-vault/README.md.gotmpl, charts/tractusx-connector-memory/README.md, charts/tractusx-connector-memory/README.md.gotmpl, charts/tractusx-connector/README.md, charts/tractusx-connector/README.md.gotmpl, edc-controlplane/edc-controlplane-base/build.gradle.kts, edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/harness/DataspaceIssuer.java, gradle/libs.versions.toml
Updates the helm chart documentation to reflect the new config values
=> fix(docs): update Helm documentation

docs/usage/management-api-walkthrough/07_edrs.md
updates `EDRs` docs with the latest changes in `0.7.x` 
document the breaking change
Closes #1231
=> chore: updates edr docs 

charts/tractusx-connector-azure-vault/README.md, charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml, charts/tractusx-connector-azure-vault/values.yaml, charts/tractusx-connector-memory/README.md, charts/tractusx-connector-memory/templates/deployment-runtime.yaml, charts/tractusx-connector-memory/values.yaml, charts/tractusx-connector/README.md, charts/tractusx-connector/templates/deployment-controlplane.yaml, charts/tractusx-connector/values.yaml
exposes trusted issuers in charts config
Closes #1236
=> feat: exposes trusted issuers in charts config

DEPENDENCIES, charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml, charts/tractusx-connector-memory/templates/deployment-runtime.yaml, charts/tractusx-connector/templates/deployment-controlplane.yaml, docs/usage/management-api-walkthrough/04_catalog.md
activate the use case HttpData push
We bundle the data plane and the also do E2E tests there
Closes #1243
=> feat: activate the use case HttpData push

DEPENDENCIES, edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/AbstractIatpConsumerPullTest.java, edc-tests/edc-controlplane/iatp-tests/src/test/java/org/eclipse/tractusx/edc/tests/transfer/iatp/harness/DataspaceIssuer.java, gradle/libs.versions.toml
=> chore: updates edc to 0.6.2

edc-extensions/iatp/tx-iatp-sts-dim/src/main/java/org/eclipse/tractusx/edc/iam/iatp/sts/dim/DimOauthClientExtension.java, edc-extensions/iatp/tx-iatp-sts-dim/src/main/java/org/eclipse/tractusx/edc/iam/iatp/sts/dim/oauth/DimOauthClientImpl.java, edc-extensions/iatp/tx-iatp-sts-dim/src/test/java/org/eclipse/tractusx/edc/iam/iatp/sts/dim/oauth/DimOauthClientImplTest.java
DIM access token cache
performance
Closes #1174
=> feat: DIM access token cache

DEPENDENCIES, edc-tests/runtime/iatp/runtime-memory-iatp-dim-ih/build.gradle.kts, edc-tests/runtime/iatp/runtime-memory-iatp-ih/build.gradle.kts, gradle/libs.versions.toml
Bumps EDC to 0.6.4
- also bumps Nimbus to 9.38
=> chore(deps): bump EDC to 0.6.4

.github/workflows/publish.yaml
adds the Mocked EDC docker image to the automatic publish workflow
=> fix(ci): add Mocked EDC to automatic artefact release

docs/usage/management-api-walkthrough/02_policies.md, docs/usage/management-api-walkthrough/07_edrs.md, docs/usage/management-api-walkthrough/08_contractagreements.md
updates policies examples according to the latest rightOperand definitions for FrameworkAgreement
=> chore: updates policies examples

edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/README.md, edc-dataplane/edc-dataplane-azure-vault/README.md, edc-dataplane/edc-dataplane-base/README.md, edc-dataplane/edc-dataplane-hashicorp-vault/README.md
Fixes all occurences of gardlew in the docs.
Continuation of #1341
=> fix(docs): fixed all occurences of gardlew

.github/actions/setup-memory-runtime/action.yml, DEPENDENCIES
fix readiness check on dast scan
dast scan job was still failing due readiness check
=> chore: fix readiness check on dast scan

gradle/libs.versions.toml
removes apache-sshd dependency
cleanup
=> chore: removes apache-sshd dep

.github/workflows/publish-openapi-ui.yml
=> docs: fix publish-ui

.github/workflows/publish-openapi-ui.yml
=> docs: fix publish openapi-ui folder

.github/dependabot.yml
=> build(dependencies): Fix dependabot docker directory

DEPENDENCIES, charts/tractusx-connector-azure-vault/README.md, charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml, charts/tractusx-connector-azure-vault/values.yaml, charts/tractusx-connector-memory/README.md, charts/tractusx-connector-memory/templates/deployment-runtime.yaml, charts/tractusx-connector-memory/values.yaml, charts/tractusx-connector/README.md, charts/tractusx-connector/templates/deployment-controlplane.yaml, charts/tractusx-connector/values.yaml, edc-controlplane/edc-controlplane-base/build.gradle.kts, edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/participant/TractusxParticipantBase.java, gradle/libs.versions.toml
feat: secure FC query API with token based auth by applying auth configuration
to all helm chart variants
Closes #1470
=> feat: secure FC query API with token based auth

.github/workflows/publish-bugfix-release.yml
Adds prepare release commit push to bugfix branch
It isn't pushing to branch and the commit is lost
=> fix(workflows): Adds prepare release commit push to bugfix branch

.github/workflows/release.yml
checkout the code before calling an action
=> fix(ci): checkout before calling action

.github/workflows/draft-release.yaml
_Briefly describe what your PR changes, which features it adds/modifies._
=> chore: backport draft-release.yaml workflow

edc-extensions/bpn-validation/bpn-validation-api/src/main/java/org/eclipse/tractusx/edc/api/bpn/v3/BusinessPartnerGroupApiV3.java
Small doc improvement
Closes #1626
=> docs: fix bpn group API example

DEPENDENCIES, edc-extensions/bdrs-client/src/test/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImplComponentTest.java
=> ci: fix ITs

.tractusx, DEPENDENCIES
Updates openApiSpecs urls
#1791 
=> docs: update the openApiSpecs urls

edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImpl.java
separate read and write locks to avoid potential deadlock as suggested by https://github.com/eclipse-tractusx/tractusx-edc/security/code-scanning/695
Part of #1926
=> fix: avoid potential deadlocks

gradle/wrapper/gradle-wrapper.properties
_Briefly describe what your PR changes, which features it adds/modifies._
dependencies update
Part of #1926
=> build(deps): bump gradle wrapper to 8.14

edc-extensions/dataplane/dataplane-proxy/edc-dataplane-proxy-consumer-api/src/main/java/org/eclipse/tractusx/edc/dataplane/proxy/consumer/api/asset/ConsumerAssetRequestController.java
Avoid security scanning warning for potential deferenced var may be null.
(no need to add coverage as the case was already covered, but refactored in a better way so codeql won't complain anymore)
Ref. https://github.com/eclipse-tractusx/tractusx-edc/security/code-scanning/603
Part of #1926
=> refactor: avoid deferenced var may be null warning

edc-extensions/bdrs-client/src/main/java/org/eclipse/tractusx/edc/identity/mapper/BdrsClientImpl.java, edc-extensions/dcp/tx-dcp-sts-dim/src/main/java/org/eclipse/tractusx/edc/iam/dcp/sts/dim/DimSecureTokenService.java, edc-extensions/dcp/tx-dcp-sts-dim/src/test/java/org/eclipse/tractusx/edc/iam/dcp/sts/dim/DimSecureTokenServiceTest.java, edc-extensions/tokenrefresh-handler/src/main/java/org/eclipse/tractusx/edc/common/tokenrefresh/TokenRefreshHandlerImpl.java, gradle/libs.versions.toml
_Briefly describe what your PR changes, which features it adds/modifies._
=> build(deps): bump EDC to 0.13.0

docs/development/decision-records/2025-08-06-contract-agreement-bpns/README.md
This PR introduces a decision record for storing participants' BPNs for each contract agreement
To document the motivation and proposed approach for persisting Business Partner Numbers alongside contract agreements
Part of #2133
=> feat: DR for storing participant's BPNs for each contract agreement

docs/development/repository-structure.md
Updates the repository structure docs as it has been untouched for quite a while.
Closes #2135
=> docs: updated repository structure

charts/tractusx-connector-memory/values.yaml, docs/usage/management-api-walkthrough/02_policies.md
updates some of the policy related documentation
Relates to #2219
=> chore: update policy constraints
